// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/relationships-one-to-one/test.crud.proto

/*
Package relationships_one_to_one is a repository.

PgSQL implementation.
*/

package relationships_one_to_one

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	pgxstdlib "github.com/jackc/pgx/v5/stdlib"
	"github.com/samlitowitz/expressions"
)

// InMemorySAInt32MAAllRepository is an in memory implementation of the SAInt32MAAllRepository interface.
type PgSQLSAInt32MAAllRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAInt32MAAllRepository to be used.
func NewPgSQLSAInt32MAAllRepository(db *sql.DB) (*PgSQLSAInt32MAAllRepository, error) {
	_, ok := db.Driver().(*pgxstdlib.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *github.com/jackc/pgx/v5/stdlib/Driver")
	}
	return &PgSQLSAInt32MAAllRepository{
		db: db,
	}, nil
}

// Create creates new SAInt32MAAlls.
// Successfully created SAInt32MAAlls are returned along with any errors that may have occurred.
func (repo *PgSQLSAInt32MAAllRepository) Create(ctx context.Context, toCreate []*SAInt32MAAll) ([]*SAInt32MAAll, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	bindsIdx := 1
	for _, saint32Maall := range toCreate {
		binds = append(binds, saint32Maall.GetSaint32Id())
		binds = append(binds, saint32Maall.GetMaallIdEnum())
		binds = append(binds, saint32Maall.GetMaallIdInt32())
		binds = append(binds, saint32Maall.GetMaallIdInt64())
		binds = append(binds, saint32Maall.GetMaallIdUint32())
		binds = append(binds, saint32Maall.GetMaallIdUint64())
		binds = append(binds, saint32Maall.GetMaallIdString())
		bindsStrs = append(bindsStrs, fmt.Sprintf("($%d, $%d, $%d, $%d, $%d, $%d, $%d)", bindsIdx+0, bindsIdx+1, bindsIdx+2, bindsIdx+3, bindsIdx+4, bindsIdx+5, bindsIdx+6))
		bindsIdx += 7
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "sa_int_32_ma_all" ("saint_32_id","maall_id_enum","maall_id_int_32","maall_id_int_64","maall_id_uint_32","maall_id_uint_64","maall_id_string") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAInt32MAAlls matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *PgSQLSAInt32MAAllRepository) Read(ctx context.Context, expr expressions.Expression) ([]*SAInt32MAAll, error) {
	query := `SELECT "saint_32_id","maall_id_enum","maall_id_int_32","maall_id_int_64","maall_id_uint_32","maall_id_uint_64","maall_id_string"
		FROM "sa_int_32_ma_all"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAInt32MAAll(expr, 1)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAInt32MAAll
	for rows.Next() {
		saint32Maall := &SAInt32MAAll_builder{}

		if err = rows.Scan(&saint32Maall.Saint32Id, &saint32Maall.MaallIdEnum, &saint32Maall.MaallIdInt32, &saint32Maall.MaallIdInt64, &saint32Maall.MaallIdUint32, &saint32Maall.MaallIdUint64, &saint32Maall.MaallIdString); err != nil {
			return nil, err
		}

		found = append(found, saint32Maall.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAInt32MAAlls based on the defined unique identifiers.
func (repo *PgSQLSAInt32MAAllRepository) Update(ctx context.Context, toUpdate []*SAInt32MAAll) ([]*SAInt32MAAll, error) {
	return nil, nil
}

// Delete deletes SAInt32MAAlls based on the defined unique identifiers
func (repo *PgSQLSAInt32MAAllRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_int_32_ma_all"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAInt32MAAll(expr, 1)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var pgsqlSAInt32MAAllColumnNameByFieldID = map[expressions.ID]string{
	Saint32Maall_Saint32Id_Field:     "saint_32_id",
	Saint32Maall_MaallIdEnum_Field:   "maall_id_enum",
	Saint32Maall_MaallIdInt32_Field:  "maall_id_int_32",
	Saint32Maall_MaallIdInt64_Field:  "maall_id_int_64",
	Saint32Maall_MaallIdUint32_Field: "maall_id_uint_32",
	Saint32Maall_MaallIdUint64_Field: "maall_id_uint_64",
	Saint32Maall_MaallIdString_Field: "maall_id_string",
}

func whereClauseFromExpressionForPgSQLSAInt32MAAll(expr expressions.Expression, paramIdx int) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAInt32MAAll(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAInt32MAAll(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAInt32MAAll(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAInt32MAAll(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForPgSQLSAInt32MAAll(expr.Operand(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAInt32MAAll(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAInt32MAAll(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAInt32MAAllFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := pgsqlSAInt32MAAllColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_int_32_ma_all"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return fmt.Sprintf("$%d", paramIdx), []any{expr.Value()}, nil
	case expressions.Timestamp:
		return fmt.Sprintf("$%d", paramIdx), []any{time.Time(expr)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}
