// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/field-mask/test.proto

/*
Package field_mask is a repository.

SQLite implementation.
*/

package field_mask

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"google.golang.org/protobuf/types/known/fieldmaskpb"
	"github.com/mennanov/fmutils"
	"modernc.org/sqlite"
	"github.com/samlitowitz/expressions"
)

// InMemorySAEnumRepository is an in memory implementation of the SAEnumRepository interface.
type SQLiteSAEnumRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAEnumRepository to be used.
func NewSQLiteSAEnumRepository(db *sql.DB) (*SQLiteSAEnumRepository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteSAEnumRepository{
		db: db,
	}, nil
}

// Create creates new SAEnums.
// Successfully created SAEnums are returned along with any errors that may have occurred.
func (repo *SQLiteSAEnumRepository) Create(ctx context.Context, toCreate []*SAEnum) ([]*SAEnum, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	noMaskBinds := []any{}
	noMaskBindsStrs := []string{}
	for _, saenum := range toCreate {
		if saenum.GetFieldMask() == nil {
			noMaskBinds = append(noMaskBinds, saenum.GetId())
			noMaskBinds = append(noMaskBinds, saenum.GetData())
			noMaskBindsStrs = append(noMaskBindsStrs, "(?,?)")
			continue
		}
		valuesByColName, err := sqliteSAEnumGetCreateValuesByColumnName(saenum, saenum.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var cols []string
		var params []string
		for colName, value := range valuesByColName {
			cols = append(cols, "\""+colName+"\"")
			params = append(params, "?")
			binds = append(binds, value)
		}
		query := fmt.Sprintf(`INSERT INTO "sa_enum" (%s) VALUES (%s)`,
			strings.Join(cols, ", "),
			strings.Join(params, ", "),
		)
		_, err = tx.ExecContext(ctx, query, binds...)
		if err != nil {
			return nil, err
		}
	}
	if len(noMaskBinds) > 0 {
		query := fmt.Sprintf(`INSERT INTO "sa_enum" ("id","data") VALUES %s`,
			strings.Join(noMaskBindsStrs, ",\n"),
		)
		_, err = tx.ExecContext(ctx, query, noMaskBinds...)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAEnums matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteSAEnumRepository) Read(ctx context.Context, expr expressions.Expression) ([]*SAEnum, error) {
	query := `SELECT "id","data"
		FROM "sa_enum"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAEnum(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAEnum
	for rows.Next() {
		saenum := &SAEnum_builder{}

		if err = rows.Scan(&saenum.Id, &saenum.Data); err != nil {
			return nil, err
		}

		found = append(found, saenum.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAEnums based on the defined unique identifiers.
func (repo *SQLiteSAEnumRepository) Update(ctx context.Context, toUpdate []*SAEnum) ([]*SAEnum, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_enum" SET "data" = ? WHERE "id" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, saenum := range toUpdate {
		if saenum.GetFieldMask() == nil {
			_, err = stmt.ExecContext(ctx, saenum.GetData(), saenum.GetId())
			if err != nil {
				return nil, err
			}
			continue
		}
		valuesByColName, err := sqliteSAEnumGetUpdateValuesByColumnName(saenum, saenum.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var setStmts []string
		for colName, value := range valuesByColName {
			setStmts = append(setStmts, fmt.Sprintf("\"%s\" = ?", colName))
			binds = append(binds, value)
		}
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				`UPDATE "sa_enum" SET %s WHERE "id" = ?`,
				strings.Join(setStmts, ", "),
			),
			append(
				binds,
				saenum.GetId(),
			)...,
		)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAEnums based on the defined unique identifiers
func (repo *SQLiteSAEnumRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_enum"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAEnum(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteSAEnumColumnNameByFieldID = map[expressions.ID]string{
	Saenum_Id_Field:   "id",
	Saenum_Data_Field: "data",
}

func whereClauseFromExpressionForSQLiteSAEnum(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAEnum(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAEnum(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAEnum(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAEnum(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteSAEnum(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAEnum(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAEnum(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAEnumFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteSAEnumColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_enum"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

func sqliteSAEnumGetCreateValuesByColumnName(def *SAEnum, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	saenum := &SAEnum{}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	valuesByColumnName["id"] = def.GetId()
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	} else {
		valuesByColumnName["data"] = saenum.GetData()
	}
	return valuesByColumnName, nil
}
func sqliteSAEnumGetUpdateValuesByColumnName(def *SAEnum, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	}
	return valuesByColumnName, nil
}

// InMemorySAInt32Repository is an in memory implementation of the SAInt32Repository interface.
type SQLiteSAInt32Repository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAInt32Repository to be used.
func NewSQLiteSAInt32Repository(db *sql.DB) (*SQLiteSAInt32Repository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteSAInt32Repository{
		db: db,
	}, nil
}

// Create creates new SAInt32s.
// Successfully created SAInt32s are returned along with any errors that may have occurred.
func (repo *SQLiteSAInt32Repository) Create(ctx context.Context, toCreate []*SAInt32) ([]*SAInt32, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	noMaskBinds := []any{}
	noMaskBindsStrs := []string{}
	for _, saint32 := range toCreate {
		if saint32.GetFieldMask() == nil {
			noMaskBinds = append(noMaskBinds, saint32.GetId())
			noMaskBinds = append(noMaskBinds, saint32.GetData())
			noMaskBindsStrs = append(noMaskBindsStrs, "(?,?)")
			continue
		}
		valuesByColName, err := sqliteSAInt32GetCreateValuesByColumnName(saint32, saint32.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var cols []string
		var params []string
		for colName, value := range valuesByColName {
			cols = append(cols, "\""+colName+"\"")
			params = append(params, "?")
			binds = append(binds, value)
		}
		query := fmt.Sprintf(`INSERT INTO "sa_int_32" (%s) VALUES (%s)`,
			strings.Join(cols, ", "),
			strings.Join(params, ", "),
		)
		_, err = tx.ExecContext(ctx, query, binds...)
		if err != nil {
			return nil, err
		}
	}
	if len(noMaskBinds) > 0 {
		query := fmt.Sprintf(`INSERT INTO "sa_int_32" ("id","data") VALUES %s`,
			strings.Join(noMaskBindsStrs, ",\n"),
		)
		_, err = tx.ExecContext(ctx, query, noMaskBinds...)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAInt32s matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteSAInt32Repository) Read(ctx context.Context, expr expressions.Expression) ([]*SAInt32, error) {
	query := `SELECT "id","data"
		FROM "sa_int_32"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAInt32(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAInt32
	for rows.Next() {
		saint32 := &SAInt32_builder{}

		if err = rows.Scan(&saint32.Id, &saint32.Data); err != nil {
			return nil, err
		}

		found = append(found, saint32.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAInt32s based on the defined unique identifiers.
func (repo *SQLiteSAInt32Repository) Update(ctx context.Context, toUpdate []*SAInt32) ([]*SAInt32, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_int_32" SET "data" = ? WHERE "id" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, saint32 := range toUpdate {
		if saint32.GetFieldMask() == nil {
			_, err = stmt.ExecContext(ctx, saint32.GetData(), saint32.GetId())
			if err != nil {
				return nil, err
			}
			continue
		}
		valuesByColName, err := sqliteSAInt32GetUpdateValuesByColumnName(saint32, saint32.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var setStmts []string
		for colName, value := range valuesByColName {
			setStmts = append(setStmts, fmt.Sprintf("\"%s\" = ?", colName))
			binds = append(binds, value)
		}
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				`UPDATE "sa_int_32" SET %s WHERE "id" = ?`,
				strings.Join(setStmts, ", "),
			),
			append(
				binds,
				saint32.GetId(),
			)...,
		)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAInt32s based on the defined unique identifiers
func (repo *SQLiteSAInt32Repository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_int_32"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAInt32(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteSAInt32ColumnNameByFieldID = map[expressions.ID]string{
	Saint32_Id_Field:   "id",
	Saint32_Data_Field: "data",
}

func whereClauseFromExpressionForSQLiteSAInt32(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAInt32(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAInt32(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAInt32(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAInt32(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteSAInt32(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAInt32(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAInt32(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAInt32Fields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteSAInt32ColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_int_32"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

func sqliteSAInt32GetCreateValuesByColumnName(def *SAInt32, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	saint32 := &SAInt32{}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	valuesByColumnName["id"] = def.GetId()
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	} else {
		valuesByColumnName["data"] = saint32.GetData()
	}
	return valuesByColumnName, nil
}
func sqliteSAInt32GetUpdateValuesByColumnName(def *SAInt32, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	}
	return valuesByColumnName, nil
}

// InMemorySAInt64Repository is an in memory implementation of the SAInt64Repository interface.
type SQLiteSAInt64Repository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAInt64Repository to be used.
func NewSQLiteSAInt64Repository(db *sql.DB) (*SQLiteSAInt64Repository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteSAInt64Repository{
		db: db,
	}, nil
}

// Create creates new SAInt64s.
// Successfully created SAInt64s are returned along with any errors that may have occurred.
func (repo *SQLiteSAInt64Repository) Create(ctx context.Context, toCreate []*SAInt64) ([]*SAInt64, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	noMaskBinds := []any{}
	noMaskBindsStrs := []string{}
	for _, saint64 := range toCreate {
		if saint64.GetFieldMask() == nil {
			noMaskBinds = append(noMaskBinds, saint64.GetId())
			noMaskBinds = append(noMaskBinds, saint64.GetData())
			noMaskBindsStrs = append(noMaskBindsStrs, "(?,?)")
			continue
		}
		valuesByColName, err := sqliteSAInt64GetCreateValuesByColumnName(saint64, saint64.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var cols []string
		var params []string
		for colName, value := range valuesByColName {
			cols = append(cols, "\""+colName+"\"")
			params = append(params, "?")
			binds = append(binds, value)
		}
		query := fmt.Sprintf(`INSERT INTO "sa_int_64" (%s) VALUES (%s)`,
			strings.Join(cols, ", "),
			strings.Join(params, ", "),
		)
		_, err = tx.ExecContext(ctx, query, binds...)
		if err != nil {
			return nil, err
		}
	}
	if len(noMaskBinds) > 0 {
		query := fmt.Sprintf(`INSERT INTO "sa_int_64" ("id","data") VALUES %s`,
			strings.Join(noMaskBindsStrs, ",\n"),
		)
		_, err = tx.ExecContext(ctx, query, noMaskBinds...)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAInt64s matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteSAInt64Repository) Read(ctx context.Context, expr expressions.Expression) ([]*SAInt64, error) {
	query := `SELECT "id","data"
		FROM "sa_int_64"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAInt64(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAInt64
	for rows.Next() {
		saint64 := &SAInt64_builder{}

		if err = rows.Scan(&saint64.Id, &saint64.Data); err != nil {
			return nil, err
		}

		found = append(found, saint64.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAInt64s based on the defined unique identifiers.
func (repo *SQLiteSAInt64Repository) Update(ctx context.Context, toUpdate []*SAInt64) ([]*SAInt64, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_int_64" SET "data" = ? WHERE "id" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, saint64 := range toUpdate {
		if saint64.GetFieldMask() == nil {
			_, err = stmt.ExecContext(ctx, saint64.GetData(), saint64.GetId())
			if err != nil {
				return nil, err
			}
			continue
		}
		valuesByColName, err := sqliteSAInt64GetUpdateValuesByColumnName(saint64, saint64.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var setStmts []string
		for colName, value := range valuesByColName {
			setStmts = append(setStmts, fmt.Sprintf("\"%s\" = ?", colName))
			binds = append(binds, value)
		}
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				`UPDATE "sa_int_64" SET %s WHERE "id" = ?`,
				strings.Join(setStmts, ", "),
			),
			append(
				binds,
				saint64.GetId(),
			)...,
		)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAInt64s based on the defined unique identifiers
func (repo *SQLiteSAInt64Repository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_int_64"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAInt64(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteSAInt64ColumnNameByFieldID = map[expressions.ID]string{
	Saint64_Id_Field:   "id",
	Saint64_Data_Field: "data",
}

func whereClauseFromExpressionForSQLiteSAInt64(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAInt64(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAInt64(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAInt64(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAInt64(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteSAInt64(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAInt64(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAInt64(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAInt64Fields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteSAInt64ColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_int_64"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

func sqliteSAInt64GetCreateValuesByColumnName(def *SAInt64, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	saint64 := &SAInt64{}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	valuesByColumnName["id"] = def.GetId()
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	} else {
		valuesByColumnName["data"] = saint64.GetData()
	}
	return valuesByColumnName, nil
}
func sqliteSAInt64GetUpdateValuesByColumnName(def *SAInt64, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	}
	return valuesByColumnName, nil
}

// InMemorySAUint32Repository is an in memory implementation of the SAUint32Repository interface.
type SQLiteSAUint32Repository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAUint32Repository to be used.
func NewSQLiteSAUint32Repository(db *sql.DB) (*SQLiteSAUint32Repository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteSAUint32Repository{
		db: db,
	}, nil
}

// Create creates new SAUint32s.
// Successfully created SAUint32s are returned along with any errors that may have occurred.
func (repo *SQLiteSAUint32Repository) Create(ctx context.Context, toCreate []*SAUint32) ([]*SAUint32, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	noMaskBinds := []any{}
	noMaskBindsStrs := []string{}
	for _, sauint32 := range toCreate {
		if sauint32.GetFieldMask() == nil {
			noMaskBinds = append(noMaskBinds, sauint32.GetId())
			noMaskBinds = append(noMaskBinds, sauint32.GetData())
			noMaskBindsStrs = append(noMaskBindsStrs, "(?,?)")
			continue
		}
		valuesByColName, err := sqliteSAUint32GetCreateValuesByColumnName(sauint32, sauint32.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var cols []string
		var params []string
		for colName, value := range valuesByColName {
			cols = append(cols, "\""+colName+"\"")
			params = append(params, "?")
			binds = append(binds, value)
		}
		query := fmt.Sprintf(`INSERT INTO "sa_uint_32" (%s) VALUES (%s)`,
			strings.Join(cols, ", "),
			strings.Join(params, ", "),
		)
		_, err = tx.ExecContext(ctx, query, binds...)
		if err != nil {
			return nil, err
		}
	}
	if len(noMaskBinds) > 0 {
		query := fmt.Sprintf(`INSERT INTO "sa_uint_32" ("id","data") VALUES %s`,
			strings.Join(noMaskBindsStrs, ",\n"),
		)
		_, err = tx.ExecContext(ctx, query, noMaskBinds...)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAUint32s matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteSAUint32Repository) Read(ctx context.Context, expr expressions.Expression) ([]*SAUint32, error) {
	query := `SELECT "id","data"
		FROM "sa_uint_32"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAUint32(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAUint32
	for rows.Next() {
		sauint32 := &SAUint32_builder{}

		if err = rows.Scan(&sauint32.Id, &sauint32.Data); err != nil {
			return nil, err
		}

		found = append(found, sauint32.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAUint32s based on the defined unique identifiers.
func (repo *SQLiteSAUint32Repository) Update(ctx context.Context, toUpdate []*SAUint32) ([]*SAUint32, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_uint_32" SET "data" = ? WHERE "id" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, sauint32 := range toUpdate {
		if sauint32.GetFieldMask() == nil {
			_, err = stmt.ExecContext(ctx, sauint32.GetData(), sauint32.GetId())
			if err != nil {
				return nil, err
			}
			continue
		}
		valuesByColName, err := sqliteSAUint32GetUpdateValuesByColumnName(sauint32, sauint32.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var setStmts []string
		for colName, value := range valuesByColName {
			setStmts = append(setStmts, fmt.Sprintf("\"%s\" = ?", colName))
			binds = append(binds, value)
		}
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				`UPDATE "sa_uint_32" SET %s WHERE "id" = ?`,
				strings.Join(setStmts, ", "),
			),
			append(
				binds,
				sauint32.GetId(),
			)...,
		)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAUint32s based on the defined unique identifiers
func (repo *SQLiteSAUint32Repository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_uint_32"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAUint32(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteSAUint32ColumnNameByFieldID = map[expressions.ID]string{
	Sauint32_Id_Field:   "id",
	Sauint32_Data_Field: "data",
}

func whereClauseFromExpressionForSQLiteSAUint32(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAUint32(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAUint32(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAUint32(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAUint32(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteSAUint32(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAUint32(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAUint32(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAUint32Fields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteSAUint32ColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_uint_32"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

func sqliteSAUint32GetCreateValuesByColumnName(def *SAUint32, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	sauint32 := &SAUint32{}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	valuesByColumnName["id"] = def.GetId()
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	} else {
		valuesByColumnName["data"] = sauint32.GetData()
	}
	return valuesByColumnName, nil
}
func sqliteSAUint32GetUpdateValuesByColumnName(def *SAUint32, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	}
	return valuesByColumnName, nil
}

// InMemorySAUint64Repository is an in memory implementation of the SAUint64Repository interface.
type SQLiteSAUint64Repository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAUint64Repository to be used.
func NewSQLiteSAUint64Repository(db *sql.DB) (*SQLiteSAUint64Repository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteSAUint64Repository{
		db: db,
	}, nil
}

// Create creates new SAUint64s.
// Successfully created SAUint64s are returned along with any errors that may have occurred.
func (repo *SQLiteSAUint64Repository) Create(ctx context.Context, toCreate []*SAUint64) ([]*SAUint64, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	noMaskBinds := []any{}
	noMaskBindsStrs := []string{}
	for _, sauint64 := range toCreate {
		if sauint64.GetFieldMask() == nil {
			noMaskBinds = append(noMaskBinds, sauint64.GetId())
			noMaskBinds = append(noMaskBinds, sauint64.GetData())
			noMaskBindsStrs = append(noMaskBindsStrs, "(?,?)")
			continue
		}
		valuesByColName, err := sqliteSAUint64GetCreateValuesByColumnName(sauint64, sauint64.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var cols []string
		var params []string
		for colName, value := range valuesByColName {
			cols = append(cols, "\""+colName+"\"")
			params = append(params, "?")
			binds = append(binds, value)
		}
		query := fmt.Sprintf(`INSERT INTO "sa_uint_64" (%s) VALUES (%s)`,
			strings.Join(cols, ", "),
			strings.Join(params, ", "),
		)
		_, err = tx.ExecContext(ctx, query, binds...)
		if err != nil {
			return nil, err
		}
	}
	if len(noMaskBinds) > 0 {
		query := fmt.Sprintf(`INSERT INTO "sa_uint_64" ("id","data") VALUES %s`,
			strings.Join(noMaskBindsStrs, ",\n"),
		)
		_, err = tx.ExecContext(ctx, query, noMaskBinds...)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAUint64s matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteSAUint64Repository) Read(ctx context.Context, expr expressions.Expression) ([]*SAUint64, error) {
	query := `SELECT "id","data"
		FROM "sa_uint_64"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAUint64(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAUint64
	for rows.Next() {
		sauint64 := &SAUint64_builder{}

		if err = rows.Scan(&sauint64.Id, &sauint64.Data); err != nil {
			return nil, err
		}

		found = append(found, sauint64.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAUint64s based on the defined unique identifiers.
func (repo *SQLiteSAUint64Repository) Update(ctx context.Context, toUpdate []*SAUint64) ([]*SAUint64, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_uint_64" SET "data" = ? WHERE "id" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, sauint64 := range toUpdate {
		if sauint64.GetFieldMask() == nil {
			_, err = stmt.ExecContext(ctx, sauint64.GetData(), sauint64.GetId())
			if err != nil {
				return nil, err
			}
			continue
		}
		valuesByColName, err := sqliteSAUint64GetUpdateValuesByColumnName(sauint64, sauint64.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var setStmts []string
		for colName, value := range valuesByColName {
			setStmts = append(setStmts, fmt.Sprintf("\"%s\" = ?", colName))
			binds = append(binds, value)
		}
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				`UPDATE "sa_uint_64" SET %s WHERE "id" = ?`,
				strings.Join(setStmts, ", "),
			),
			append(
				binds,
				sauint64.GetId(),
			)...,
		)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAUint64s based on the defined unique identifiers
func (repo *SQLiteSAUint64Repository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_uint_64"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAUint64(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteSAUint64ColumnNameByFieldID = map[expressions.ID]string{
	Sauint64_Id_Field:   "id",
	Sauint64_Data_Field: "data",
}

func whereClauseFromExpressionForSQLiteSAUint64(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAUint64(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAUint64(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAUint64(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAUint64(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteSAUint64(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAUint64(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAUint64(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAUint64Fields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteSAUint64ColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_uint_64"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

func sqliteSAUint64GetCreateValuesByColumnName(def *SAUint64, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	sauint64 := &SAUint64{}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	valuesByColumnName["id"] = def.GetId()
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	} else {
		valuesByColumnName["data"] = sauint64.GetData()
	}
	return valuesByColumnName, nil
}
func sqliteSAUint64GetUpdateValuesByColumnName(def *SAUint64, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	}
	return valuesByColumnName, nil
}

// InMemorySAStringRepository is an in memory implementation of the SAStringRepository interface.
type SQLiteSAStringRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAStringRepository to be used.
func NewSQLiteSAStringRepository(db *sql.DB) (*SQLiteSAStringRepository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteSAStringRepository{
		db: db,
	}, nil
}

// Create creates new SAStrings.
// Successfully created SAStrings are returned along with any errors that may have occurred.
func (repo *SQLiteSAStringRepository) Create(ctx context.Context, toCreate []*SAString) ([]*SAString, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	noMaskBinds := []any{}
	noMaskBindsStrs := []string{}
	for _, sastring := range toCreate {
		if sastring.GetFieldMask() == nil {
			noMaskBinds = append(noMaskBinds, sastring.GetId())
			noMaskBinds = append(noMaskBinds, sastring.GetData())
			noMaskBindsStrs = append(noMaskBindsStrs, "(?,?)")
			continue
		}
		valuesByColName, err := sqliteSAStringGetCreateValuesByColumnName(sastring, sastring.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var cols []string
		var params []string
		for colName, value := range valuesByColName {
			cols = append(cols, "\""+colName+"\"")
			params = append(params, "?")
			binds = append(binds, value)
		}
		query := fmt.Sprintf(`INSERT INTO "sa_string" (%s) VALUES (%s)`,
			strings.Join(cols, ", "),
			strings.Join(params, ", "),
		)
		_, err = tx.ExecContext(ctx, query, binds...)
		if err != nil {
			return nil, err
		}
	}
	if len(noMaskBinds) > 0 {
		query := fmt.Sprintf(`INSERT INTO "sa_string" ("id","data") VALUES %s`,
			strings.Join(noMaskBindsStrs, ",\n"),
		)
		_, err = tx.ExecContext(ctx, query, noMaskBinds...)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAStrings matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteSAStringRepository) Read(ctx context.Context, expr expressions.Expression) ([]*SAString, error) {
	query := `SELECT "id","data"
		FROM "sa_string"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAString(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAString
	for rows.Next() {
		sastring := &SAString_builder{}

		if err = rows.Scan(&sastring.Id, &sastring.Data); err != nil {
			return nil, err
		}

		found = append(found, sastring.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAStrings based on the defined unique identifiers.
func (repo *SQLiteSAStringRepository) Update(ctx context.Context, toUpdate []*SAString) ([]*SAString, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_string" SET "data" = ? WHERE "id" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, sastring := range toUpdate {
		if sastring.GetFieldMask() == nil {
			_, err = stmt.ExecContext(ctx, sastring.GetData(), sastring.GetId())
			if err != nil {
				return nil, err
			}
			continue
		}
		valuesByColName, err := sqliteSAStringGetUpdateValuesByColumnName(sastring, sastring.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var setStmts []string
		for colName, value := range valuesByColName {
			setStmts = append(setStmts, fmt.Sprintf("\"%s\" = ?", colName))
			binds = append(binds, value)
		}
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				`UPDATE "sa_string" SET %s WHERE "id" = ?`,
				strings.Join(setStmts, ", "),
			),
			append(
				binds,
				sastring.GetId(),
			)...,
		)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAStrings based on the defined unique identifiers
func (repo *SQLiteSAStringRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_string"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteSAString(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteSAStringColumnNameByFieldID = map[expressions.ID]string{
	Sastring_Id_Field:   "id",
	Sastring_Data_Field: "data",
}

func whereClauseFromExpressionForSQLiteSAString(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAString(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAString(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAString(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAString(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteSAString(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteSAString(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteSAString(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAStringFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteSAStringColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_string"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

func sqliteSAStringGetCreateValuesByColumnName(def *SAString, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	sastring := &SAString{}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	valuesByColumnName["id"] = def.GetId()
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	} else {
		valuesByColumnName["data"] = sastring.GetData()
	}
	return valuesByColumnName, nil
}
func sqliteSAStringGetUpdateValuesByColumnName(def *SAString, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id")
	}
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	}
	return valuesByColumnName, nil
}

// InMemoryMAAllRepository is an in memory implementation of the MAAllRepository interface.
type SQLiteMAAllRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemoryMAAllRepository to be used.
func NewSQLiteMAAllRepository(db *sql.DB) (*SQLiteMAAllRepository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteMAAllRepository{
		db: db,
	}, nil
}

// Create creates new MAAlls.
// Successfully created MAAlls are returned along with any errors that may have occurred.
func (repo *SQLiteMAAllRepository) Create(ctx context.Context, toCreate []*MAAll) ([]*MAAll, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	noMaskBinds := []any{}
	noMaskBindsStrs := []string{}
	for _, maall := range toCreate {
		if maall.GetFieldMask() == nil {
			noMaskBinds = append(noMaskBinds, maall.GetIdEnum())
			noMaskBinds = append(noMaskBinds, maall.GetIdInt32())
			noMaskBinds = append(noMaskBinds, maall.GetIdInt64())
			noMaskBinds = append(noMaskBinds, maall.GetIdUint32())
			noMaskBinds = append(noMaskBinds, maall.GetIdUint64())
			noMaskBinds = append(noMaskBinds, maall.GetIdString())
			noMaskBinds = append(noMaskBinds, maall.GetData())
			noMaskBindsStrs = append(noMaskBindsStrs, "(?,?,?,?,?,?,?)")
			continue
		}
		valuesByColName, err := sqliteMAAllGetCreateValuesByColumnName(maall, maall.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var cols []string
		var params []string
		for colName, value := range valuesByColName {
			cols = append(cols, "\""+colName+"\"")
			params = append(params, "?")
			binds = append(binds, value)
		}
		query := fmt.Sprintf(`INSERT INTO "ma_all" (%s) VALUES (%s)`,
			strings.Join(cols, ", "),
			strings.Join(params, ", "),
		)
		_, err = tx.ExecContext(ctx, query, binds...)
		if err != nil {
			return nil, err
		}
	}
	if len(noMaskBinds) > 0 {
		query := fmt.Sprintf(`INSERT INTO "ma_all" ("id_enum","id_int_32","id_int_64","id_uint_32","id_uint_64","id_string","data") VALUES %s`,
			strings.Join(noMaskBindsStrs, ",\n"),
		)
		_, err = tx.ExecContext(ctx, query, noMaskBinds...)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of MAAlls matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteMAAllRepository) Read(ctx context.Context, expr expressions.Expression) ([]*MAAll, error) {
	query := `SELECT "id_enum","id_int_32","id_int_64","id_uint_32","id_uint_64","id_string","data"
		FROM "ma_all"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteMAAll(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*MAAll
	for rows.Next() {
		maall := &MAAll_builder{}

		if err = rows.Scan(&maall.IdEnum, &maall.IdInt32, &maall.IdInt64, &maall.IdUint32, &maall.IdUint64, &maall.IdString, &maall.Data); err != nil {
			return nil, err
		}

		found = append(found, maall.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing MAAlls based on the defined unique identifiers.
func (repo *SQLiteMAAllRepository) Update(ctx context.Context, toUpdate []*MAAll) ([]*MAAll, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "ma_all" SET "data" = ? WHERE "id_enum" = ? AND "id_int_32" = ? AND "id_int_64" = ? AND "id_uint_32" = ? AND "id_uint_64" = ? AND "id_string" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, maall := range toUpdate {
		if maall.GetFieldMask() == nil {
			_, err = stmt.ExecContext(ctx, maall.GetData(), maall.GetIdEnum(), maall.GetIdInt32(), maall.GetIdInt64(), maall.GetIdUint32(), maall.GetIdUint64(), maall.GetIdString())
			if err != nil {
				return nil, err
			}
			continue
		}
		valuesByColName, err := sqliteMAAllGetUpdateValuesByColumnName(maall, maall.GetFieldMask())
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var setStmts []string
		for colName, value := range valuesByColName {
			setStmts = append(setStmts, fmt.Sprintf("\"%s\" = ?", colName))
			binds = append(binds, value)
		}
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				`UPDATE "ma_all" SET %s WHERE "id_enum" = ? AND "id_int_32" = ? AND "id_int_64" = ? AND "id_uint_32" = ? AND "id_uint_64" = ? AND "id_string" = ?`,
				strings.Join(setStmts, ", "),
			),
			append(
				binds,
				maall.GetIdEnum(), maall.GetIdInt32(), maall.GetIdInt64(), maall.GetIdUint32(), maall.GetIdUint64(), maall.GetIdString(),
			)...,
		)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes MAAlls based on the defined unique identifiers
func (repo *SQLiteMAAllRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "ma_all"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteMAAll(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteMAAllColumnNameByFieldID = map[expressions.ID]string{
	Maall_IdEnum_Field:   "id_enum",
	Maall_IdInt32_Field:  "id_int_32",
	Maall_IdInt64_Field:  "id_int_64",
	Maall_IdUint32_Field: "id_uint_32",
	Maall_IdUint64_Field: "id_uint_64",
	Maall_IdString_Field: "id_string",
	Maall_Data_Field:     "data",
}

func whereClauseFromExpressionForSQLiteMAAll(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteMAAll(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteMAAll(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteMAAll(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteMAAll(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteMAAll(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteMAAll(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteMAAll(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validMAAllFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteMAAllColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"ma_all"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

func sqliteMAAllGetCreateValuesByColumnName(def *MAAll, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	maall := &MAAll{}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id_enum"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_enum")
	}
	valuesByColumnName["id_enum"] = def.GetIdEnum()
	if _, ok := nestedMask["id_int32"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_int32")
	}
	valuesByColumnName["id_int_32"] = def.GetIdInt32()
	if _, ok := nestedMask["id_int64"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_int64")
	}
	valuesByColumnName["id_int_64"] = def.GetIdInt64()
	if _, ok := nestedMask["id_uint32"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_uint32")
	}
	valuesByColumnName["id_uint_32"] = def.GetIdUint32()
	if _, ok := nestedMask["id_uint64"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_uint64")
	}
	valuesByColumnName["id_uint_64"] = def.GetIdUint64()
	if _, ok := nestedMask["id_string"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_string")
	}
	valuesByColumnName["id_string"] = def.GetIdString()
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	} else {
		valuesByColumnName["data"] = maall.GetData()
	}
	return valuesByColumnName, nil
}
func sqliteMAAllGetUpdateValuesByColumnName(def *MAAll, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id_enum"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_enum")
	}
	if _, ok := nestedMask["id_int32"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_int32")
	}
	if _, ok := nestedMask["id_int64"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_int64")
	}
	if _, ok := nestedMask["id_uint32"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_uint32")
	}
	if _, ok := nestedMask["id_uint64"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_uint64")
	}
	if _, ok := nestedMask["id_string"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: id_string")
	}
	if _, ok := nestedMask["data"]; ok {
		valuesByColumnName["data"] = def.GetData()
	}
	return valuesByColumnName, nil
}
