// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.0
// source: protoc-gen-crud/options/relationships/type.proto

package relationships

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_UNKNOWN_TYPE Type = 0
	Type_ONE_TO_ONE   Type = 1
	Type_ONE_TO_MANY  Type = 2
	Type_MANY_TO_ONE  Type = 3
	Type_MANY_TO_MANY Type = 4
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "ONE_TO_ONE",
		2: "ONE_TO_MANY",
		3: "MANY_TO_ONE",
		4: "MANY_TO_MANY",
	}
	Type_value = map[string]int32{
		"UNKNOWN_TYPE": 0,
		"ONE_TO_ONE":   1,
		"ONE_TO_MANY":  2,
		"MANY_TO_ONE":  3,
		"MANY_TO_MANY": 4,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_protoc_gen_crud_options_relationships_type_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_protoc_gen_crud_options_relationships_type_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_protoc_gen_crud_options_relationships_type_proto_rawDescGZIP(), []int{0}
}

var File_protoc_gen_crud_options_relationships_type_proto protoreflect.FileDescriptor

var file_protoc_gen_crud_options_relationships_type_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x63, 0x72, 0x75,
	0x64, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x5f, 0x63,
	0x72, 0x75, 0x64, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x72, 0x65, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x2a, 0x5c, 0x0a, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4f, 0x4e, 0x45, 0x5f, 0x54, 0x4f, 0x5f, 0x4f, 0x4e,
	0x45, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x4f, 0x4e, 0x45, 0x5f, 0x54, 0x4f, 0x5f, 0x4d, 0x41,
	0x4e, 0x59, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4d, 0x41, 0x4e, 0x59, 0x5f, 0x54, 0x4f, 0x5f,
	0x4f, 0x4e, 0x45, 0x10, 0x03, 0x12, 0x10, 0x0a, 0x0c, 0x4d, 0x41, 0x4e, 0x59, 0x5f, 0x54, 0x4f,
	0x5f, 0x4d, 0x41, 0x4e, 0x59, 0x10, 0x04, 0x42, 0x3e, 0x5a, 0x3c, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6d, 0x6c, 0x69, 0x74, 0x6f, 0x77, 0x69, 0x74,
	0x7a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x63, 0x72, 0x75,
	0x64, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x68, 0x69, 0x70, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_gen_crud_options_relationships_type_proto_rawDescOnce sync.Once
	file_protoc_gen_crud_options_relationships_type_proto_rawDescData = file_protoc_gen_crud_options_relationships_type_proto_rawDesc
)

func file_protoc_gen_crud_options_relationships_type_proto_rawDescGZIP() []byte {
	file_protoc_gen_crud_options_relationships_type_proto_rawDescOnce.Do(func() {
		file_protoc_gen_crud_options_relationships_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_gen_crud_options_relationships_type_proto_rawDescData)
	})
	return file_protoc_gen_crud_options_relationships_type_proto_rawDescData
}

var file_protoc_gen_crud_options_relationships_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protoc_gen_crud_options_relationships_type_proto_goTypes = []interface{}{
	(Type)(0), // 0: protoc_gen_crud.options.relationships.Type
}
var file_protoc_gen_crud_options_relationships_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_gen_crud_options_relationships_type_proto_init() }
func file_protoc_gen_crud_options_relationships_type_proto_init() {
	if File_protoc_gen_crud_options_relationships_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_gen_crud_options_relationships_type_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protoc_gen_crud_options_relationships_type_proto_goTypes,
		DependencyIndexes: file_protoc_gen_crud_options_relationships_type_proto_depIdxs,
		EnumInfos:         file_protoc_gen_crud_options_relationships_type_proto_enumTypes,
	}.Build()
	File_protoc_gen_crud_options_relationships_type_proto = out.File
	file_protoc_gen_crud_options_relationships_type_proto_rawDesc = nil
	file_protoc_gen_crud_options_relationships_type_proto_goTypes = nil
	file_protoc_gen_crud_options_relationships_type_proto_depIdxs = nil
}
