package crud

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/samlitowitz/protoc-gen-crud/internal/generator/crud"

	crudOptions "github.com/samlitowitz/protoc-gen-crud/options"

	"github.com/samlitowitz/protoc-gen-crud/internal/casing"
	"github.com/samlitowitz/protoc-gen-crud/internal/descriptor"

	genSQLite "github.com/samlitowitz/protoc-gen-crud/internal/generator/sqlite"

	"github.com/iancoleman/strcase"
)

func init() {
	strcase.ConfigureAcronym("UID", "uid")
}

func protoFieldAccessorFn(f *descriptor.Field) string {
	return fmt.Sprintf("Get%s()", casing.CamelIdentifier(f.GetName()))
}

func protoFieldField(f *descriptor.Field) string {
	return casing.CamelIdentifier(f.GetName())
}

type param struct {
	*descriptor.File
	Imports []descriptor.GoPackage
}

type message struct {
	*descriptor.Message
}

func applyTemplate(p param, reg *descriptor.Registry) (string, error) {
	w := bytes.NewBuffer(nil)
	if err := headerTemplate.Execute(w, p); err != nil {
		return "", fmt.Errorf("header: %v", err)
	}

	for _, msg := range p.Messages {
		if !msg.GenerateCRUD {
			continue
		}
		if _, ok := msg.Implementations[crudOptions.Implementation_SQLITE]; !ok {
			continue
		}

		if err := repositoryTemplate.Execute(w, &message{msg}); err != nil {
			return "", fmt.Errorf(" message %s: repository: %v", msg.GetName(), err)
		}
	}

	return w.String(), nil
}

var (
	headerTemplate = template.Must(template.New("header").Parse(`
// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: {{.GetName}}

/*
Package {{.GoPkg.Name}} is a repository.

SQLite implementation.
*/

package {{.GoPkg.Name}}
{{if .Imports}}
import (
	{{range $i := .Imports}}{{if $i.Standard}}{{$i | printf "%s\n"}}{{end}}{{end}}

	{{range $i := .Imports}}{{if not $i.Standard}}{{$i | printf "%s\n"}}{{end}}{{end}}
)
{{end}}
`))

	repositoryTemplate = template.Must(template.New("repository").Parse(`
{{template "repository-struct" .}}

{{template "repository-create" .}}

{{template "repository-read" .}}

{{template "repository-update" .}}

{{template "repository-delete" .}}

{{template "repository-misc" .}}
`))

	_ = template.Must(repositoryTemplate.New("repository-struct").Parse(`
// InMemory{{.GetName}}Repository is an in memory implementation of the {{.GetName}}Repository interface.
type SQLite{{.GetName}}Repository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemory{{.GetName}}Repository to be used.
func NewSQLite{{.GetName}}Repository(db *sql.DB) (*SQLite{{.GetName}}Repository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLite{{.GetName}}Repository{
		db: db,
	}, nil
}
`))

	funcMap template.FuncMap = map[string]interface{}{
		"camelIdentifier": casing.CamelIdentifier,
		"toLowerCamel":    strcase.ToLowerCamel,

		"fieldIDConstantName":  crud.FieldIDConstantName,
		"fieldIDConstantValue": crud.FieldIDConstantValue,
		"protoFieldAccessor":   protoFieldAccessorFn,
		"protoFieldField":      protoFieldField,
		"sqlQuotedIdent":       genSQLite.SQLiteQuotedIdent,
		"sqlIdent":             genSQLite.SQLiteIdent,
	}

	_ = template.Must(repositoryTemplate.New("repository-create").Funcs(funcMap).Parse(`
// Create creates new {{.GetName}}s.
// Successfully created {{.GetName}}s are returned along with any errors that may have occurred.
func (repo *SQLite{{.GetName}}Repository) Create(ctx context.Context, toCreate []*{{.GoType .File.GoPkg.Path}}) ([]*{{.GoType .File.GoPkg.Path}}, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	{{- if .HasFieldMask -}}
	{{template "repository-create-field-mask" .}}
	{{- else -}}
	{{template "repository-create-no-field-mask" .}}
	{{- end -}}

	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}
`))

	_ = template.Must(repositoryTemplate.New("repository-create-no-field-mask").Funcs(funcMap).Parse(`
	binds := []any{}
	bindsStrs := []string{}
	for _, {{toLowerCamel .GetName}} := range toCreate {
		{{- range $field := .PrimaryKey}}
		binds = append(binds, {{toLowerCamel $.GetName}}.{{protoFieldAccessor $field}})
		{{- end}}
		{{- range $field := .NonPrimeAttributes}}
		binds = append(binds, {{toLowerCamel $.GetName}}.{{protoFieldAccessor $field}})
		{{- end}}
		bindsStrs = append(bindsStrs, "(
			{{- range $i, $field := .PrimaryKey -}}
			{{if $i}},{{end}}?
			{{- end -}}
			{{- if and (gt (len .PrimaryKey) 0) (gt (len .NonPrimeAttributes) 0) -}},{{- end -}}
			{{- range $i, $field := .NonPrimeAttributes -}}
			{{if $i}},{{end}}?
			{{- end -}}
		)")
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			` + "`" + `INSERT INTO {{sqlQuotedIdent .GetName}} (
			{{- range $i, $field := .PrimaryKey -}}
				{{- if $i}},{{end}}{{sqlQuotedIdent $field.GetName}}
			{{- end -}}
			{{- if and (gt (len .PrimaryKey) 0) (gt (len .NonPrimeAttributes) 0) -}},{{- end -}}
			{{- range $i, $field := .NonPrimeAttributes -}}
				{{- if $i}},{{end}}{{sqlQuotedIdent $field.GetName}}
			{{- end -}}) VALUES
			%s` + "`" + `,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...
	)
	if err != nil {
		return nil, err
	}
`))

	_ = template.Must(repositoryTemplate.New("repository-create-field-mask").Funcs(funcMap).Parse(`
	noMaskBinds := []any{}
	noMaskBindsStrs := []string{}
	for _, {{toLowerCamel $.GetName}} := range toCreate {
		if {{toLowerCamel $.GetName}}.{{camelIdentifier $.FieldMask.GetName}} == nil {
			{{- range $field := .PrimaryKey}}
			noMaskBinds = append(noMaskBinds, {{toLowerCamel $.GetName}}.{{protoFieldAccessor $field}})
			{{- end}}
			{{- range $field := .NonPrimeAttributes}}
			noMaskBinds = append(noMaskBinds, {{toLowerCamel $.GetName}}.{{protoFieldAccessor $field}})
			{{- end}}
			noMaskBindsStrs = append(noMaskBindsStrs, "(
			{{- range $i, $field := .PrimaryKey -}}
			{{if $i}},{{end}}?
			{{- end -}}
			{{- if and (gt (len .PrimaryKey) 0) (gt (len .NonPrimeAttributes) 0) -}},{{- end -}}
			{{- range $i, $field := .NonPrimeAttributes -}}
			{{if $i}},{{end}}?
			{{- end -}}
			)")
			continue
		}
		valuesByColName, err := sqlite{{.GetName}}GetCreateValuesByColumnName({{toLowerCamel $.GetName}}, {{toLowerCamel $.GetName}}.{{camelIdentifier $.FieldMask.GetName}})
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var cols []string
		var params []string
		for colName, value := range valuesByColName {
			cols = append(cols, "\"" + colName + "\"")
			params = append(params, "?")
			binds = append(binds, value)
		}
		query := fmt.Sprintf(` + "`" + `INSERT INTO {{sqlQuotedIdent .GetName}} (%s) VALUES (%s)` + "`" + `,
			strings.Join(cols, ", "),
			strings.Join(params, ", "),
		)
		_, err = tx.ExecContext(ctx, query, binds...)
		if err != nil {
			return nil, err
		}
	}
	if len(noMaskBinds) > 0 {
		query := fmt.Sprintf(` + "`" + `INSERT INTO {{sqlQuotedIdent .GetName}} (
			{{- range $i, $field := .PrimaryKey -}}
			{{if $i}},{{end}}{{sqlQuotedIdent $field.GetName}}
			{{- end -}}
			{{- if and (gt (len .PrimaryKey) 0) (gt (len .NonPrimeAttributes) 0) -}},{{- end -}}
			{{- range $i, $field := .NonPrimeAttributes -}}
			{{if $i}},{{end}}{{sqlQuotedIdent $field.GetName}}
			{{- end -}}
			) VALUES %s` + "`" + `,
			strings.Join(noMaskBindsStrs, ",\n"),
		)
		_, err = tx.ExecContext(ctx, query, noMaskBinds...)
		if err != nil {
			return nil, err
		}
	}
`))

	_ = template.Must(repositoryTemplate.New("repository-read").Funcs(funcMap).Parse(`
// Read returns a set of {{.GetName}}s matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLite{{.GetName}}Repository) Read(ctx context.Context, expr expressions.Expression) ([]*{{.GoType .File.GoPkg.Path}}, error) {
	query := ` + "`" + `SELECT {{ range $i, $field := .PrimaryKey -}}
		{{if $i}},{{end}}{{sqlQuotedIdent $field.GetName}}
		{{- end -}}
		{{- if and (gt (len .PrimaryKey) 0) (gt (len .NonPrimeAttributes) 0) -}},{{- end -}}
		{{- range $i, $field := .NonPrimeAttributes -}}
		{{if $i}},{{end}}{{sqlQuotedIdent $field.GetName}}
		{{- end }}
		FROM {{sqlQuotedIdent .GetName}}
` + "`" + `
	clauses, binds, err := whereClauseFromExpressionFor{{.GetName}}(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*{{.GoType .File.GoPkg.Path}}
	for rows.Next() {
		{{toLowerCamel .GetName}} := &{{.GoType .File.GoPkg.Path}}{
			{{range $i, $field := .NonPrimeAttributes -}}
			{{if $field.HasRelationship}}{{camelIdentifier $field.GetName}}: &{{$field.FieldMessage.GoType $.File.GoPkg.Path}}{},{{end}}
			{{- end}}
		}
		if err = rows.Scan(
		{{- range $i, $field := .PrimaryKey -}}
		{{if $i}},{{end}} &{{toLowerCamel $.GetName}}.{{protoFieldField $field}}
		{{- end -}}
		{{- if and (gt (len .PrimaryKey) 0) (gt (len .NonPrimeAttributes) 0) -}},{{- end -}}
		{{- range $i, $field := .NonPrimeAttributes -}}
		{{if $i}},{{end}} &{{toLowerCamel $.GetName}}.{{protoFieldField $field}}
		{{- end -}}
		); err != nil {
			return nil, err
		}
		found = append(found, {{toLowerCamel .GetName}})
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}
`))

	_ = template.Must(repositoryTemplate.New("repository-update").Funcs(funcMap).Parse(`
// Update modifies existing {{.GetName}}s based on the defined unique identifiers.
func (repo *SQLite{{.GetName}}Repository) Update(ctx context.Context, toUpdate []*{{.GoType .File.GoPkg.Path}}) ([]*{{.GoType .File.GoPkg.Path}}, error) {
	{{- if eq (len .NonPrimeAttributes) 0 -}}
	return nil, nil
	{{- else -}}
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		` + "`" + `UPDATE {{sqlQuotedIdent .GetName}} SET {{range $i, $field := .NonPrimeAttributes -}}
		{{if $i}},{{end}}{{sqlQuotedIdent $field.GetName}} = ?
		{{- end }} WHERE {{ range $i, $field := .PrimaryKey -}}
		{{if $i}} AND {{end}}{{sqlQuotedIdent $field.GetName}} = ?
		{{- end }}` + "`" + `,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	{{- if .HasFieldMask -}}
	{{ template "repository-update-field-mask" .}}
	{{- else -}}
	{{ template "repository-update-no-field-mask" .}}
	{{- end -}}

	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
	{{- end -}}
}
`))

	_ = template.Must(repositoryTemplate.New("repository-update-no-field-mask").Funcs(funcMap).Parse(`
	for _, {{toLowerCamel .GetName}} := range toUpdate {
		_, err = stmt.ExecContext(ctx, {{ range $i, $field := .NonPrimeAttributes -}}
		{{if $i}},{{end}}{{toLowerCamel $.GetName}}.{{protoFieldAccessor $field}}
		{{- end }},{{ range $i, $field := .PrimaryKey -}}
		{{if $i}},{{end}}{{toLowerCamel $.GetName}}.{{protoFieldAccessor $field}}
		{{- end }})
		if err != nil {
			return nil, err
		}
	}
`))

	_ = template.Must(repositoryTemplate.New("repository-update-field-mask").Funcs(funcMap).Parse(`
	for _, {{toLowerCamel .GetName}} := range toUpdate {
		if {{toLowerCamel .GetName}}.{{camelIdentifier .FieldMask.GetName}} == nil {
			_, err = stmt.ExecContext(ctx, {{ range $i, $field := .NonPrimeAttributes -}}
			{{if $i}},{{end}}{{toLowerCamel $.GetName}}.{{protoFieldAccessor $field}}
			{{- end }},{{ range $i, $field := .PrimaryKey -}}
			{{if $i}},{{end}}{{toLowerCamel $.GetName}}.{{protoFieldAccessor $field}}
			{{- end }})
			if err != nil {
				return nil, err
			}
			continue
		}
		valuesByColName, err := sqlite{{.GetName}}GetUpdateValuesByColumnName({{toLowerCamel .GetName}}, {{toLowerCamel .GetName}}.{{camelIdentifier .FieldMask.GetName}})
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var setStmts []string
		for colName, value := range valuesByColName {
			setStmts = append(setStmts, fmt.Sprintf("\"%s\" = ?", colName))
			binds = append(binds, value)
		}
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				` + "`" + `UPDATE {{sqlQuotedIdent .GetName}} SET %s WHERE {{ range $i, $field := .PrimaryKey -}}
				{{if $i}} AND {{end}}{{sqlQuotedIdent $field.GetName}} = ?
				{{- end }}` + "`" + `,
				strings.Join(setStmts, ", "),
			),
			append(
				binds,
				{{ range $i, $field := .PrimaryKey -}}
				{{if $i}},{{end}}{{toLowerCamel $.GetName}}.Get{{camelIdentifier $field.GetName}}()
				{{- end }},
			)...
		)
		if err != nil {
			return nil, err
		}
	}
`))

	_ = template.Must(repositoryTemplate.New("repository-delete").Funcs(funcMap).Parse(`
// Delete deletes {{.GetName}}s based on the defined unique identifiers
func (repo *SQLite{{.GetName}}Repository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := ` + "`" + `DELETE FROM {{sqlQuotedIdent .GetName}}` + "`" + `
	clauses, binds, err := whereClauseFromExpressionFor{{.GetName}}(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}
`))

	_ = template.Must(repositoryTemplate.New("repository-misc").Funcs(funcMap).Parse(`
var sqlite{{.GetName}}ColumnNameByFieldID = map[expressions.FieldID]string{
{{- range $field := .Fields}}
	{{fieldIDConstantName $field}}: "{{sqlIdent $field.GetName}}",
{{- end}}
}

func whereClauseFromExpressionFor{{.GetName}}(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
		case *expressions.And:
			left, leftBinds, err := whereClauseFromExpressionFor{{.GetName}}(expr.Left())
			if err != nil {
				return "", nil, err
			}
			right, rightBinds, err := whereClauseFromExpressionFor{{.GetName}}(expr.Right())
			if err != nil {
				return "", nil, err
			}
			return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

		case *expressions.Or:
				left, leftBinds, err := whereClauseFromExpressionFor{{.GetName}}(expr.Left())
			if err != nil {
				return "", nil, err
			}
			right, rightBinds, err := whereClauseFromExpressionFor{{.GetName}}(expr.Right())
			if err != nil {
				return "", nil, err
			}
			return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
		case *expressions.Not:
			operand, binds, err := whereClauseFromExpressionFor{{.GetName}}(expr.Operand())
			if err != nil {
				return "", nil, err
			}
			return fmt.Sprintf("NOT %s", operand), binds, nil

		case *expressions.Equal:
				left, leftBinds, err := whereClauseFromExpressionFor{{.GetName}}(expr.Left())
			if err != nil {
				return "", nil, err
			}
			right, rightBinds, err := whereClauseFromExpressionFor{{.GetName}}(expr.Right())
			if err != nil {
				return "", nil, err
			}
			return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

		case *expressions.Identifier:
			if _, ok := valid{{.GetName}}Fields[expr.ID()]; !ok {
				return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
			}
			colName, ok := sqlite{{.GetName}}ColumnNameByFieldID[expr.ID()]
			if !ok {
				return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
			}
			return fmt.Sprintf(` + "`" + `{{sqlQuotedIdent .GetName}}."%s"` + "`" + `,colName), nil, nil
		case *expressions.Scalar:
			return "?", []any{expr.Value()}, nil
		default:
			return "", nil, fmt.Errorf("unknown expression")
	}
}

{{if .HasFieldMask}}
func sqlite{{.GetName}}GetCreateValuesByColumnName(def *{{.GoType .File.GoPkg.Path}}, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	{{toLowerCamel $.GetName}} := &{{.GoType .File.GoPkg.Path}}{}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	{{ range $i, $field := .PrimaryKey -}}
	if _, ok := nestedMask["{{$field.GetName}}"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: {{$field.GetName}}")
	}
	valuesByColumnName["{{sqlIdent $field.GetName}}"] = def.{{protoFieldAccessor $field}}
	{{end -}}
	{{ range $i, $field := .NonPrimeAttributes -}}
	if _, ok := nestedMask["{{$field.GetName}}"]; ok {
		valuesByColumnName["{{sqlIdent $field.GetName}}"] = def.{{protoFieldAccessor $field}}
	} else {
		valuesByColumnName["{{sqlIdent $field.GetName}}"] = {{toLowerCamel $.GetName}}.{{protoFieldAccessor $field}}
	}
	{{end -}}
	return valuesByColumnName, nil
}
func sqlite{{.GetName}}GetUpdateValuesByColumnName(def *{{.GoType .File.GoPkg.Path}}, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	{{ range $i, $field := .PrimaryKey -}}
	if _, ok := nestedMask["{{$field.GetName}}"]; !ok {
		return nil, fmt.Errorf("primary key field excluded by field mask: {{$field.GetName}}")
	}
	{{end -}}
	{{ range $i, $field := .NonPrimeAttributes -}}
	if _, ok := nestedMask["{{$field.GetName}}"]; ok {
		valuesByColumnName["{{sqlIdent $field.GetName}}"] = def.{{protoFieldAccessor $field}}
	}
	{{end -}}
	return valuesByColumnName, nil
}
{{end}}
`))
)
