// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: protoc-gen-crud/examples/link-via-unique-id-single/user.proto

/*
Package link_via_unique_id_single is a repository.

It provides an interface to implement.
*/

package link_via_unique_id_single
