// Code generated by "stringer -type=Typ"; DO NOT EDIT.

package attribute

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNKNOWN-0]
	_ = x[BOOL-1]
	_ = x[BYTE-2]
	_ = x[INTEGER-3]
	_ = x[FLOAT-4]
	_ = x[STRING-5]
}

const _Typ_name = "UNKNOWNBOOLBYTEINTEGERFLOATSTRING"

var _Typ_index = [...]uint8{0, 7, 11, 15, 22, 27, 33}

func (i Typ) String() string {
	if i < 0 || i >= Typ(len(_Typ_index)-1) {
		return "Typ(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Typ_name[_Typ_index[i]:_Typ_index[i+1]]
}
