// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/as-timestamp-field/test.proto

/*
Package as_timestamp_field is a repository.

SQLite implementation.
*/

package as_timestamp_field

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
	"modernc.org/sqlite"
	"github.com/samlitowitz/expressions"
)

// InMemoryAsTimestampRepository is an in memory implementation of the AsTimestampRepository interface.
type SQLiteAsTimestampRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemoryAsTimestampRepository to be used.
func NewSQLiteAsTimestampRepository(db *sql.DB) (*SQLiteAsTimestampRepository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteAsTimestampRepository{
		db: db,
	}, nil
}

// Create creates new AsTimestamps.
// Successfully created AsTimestamps are returned along with any errors that may have occurred.
func (repo *SQLiteAsTimestampRepository) Create(ctx context.Context, toCreate []*AsTimestamp) ([]*AsTimestamp, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	for _, asTimestamp := range toCreate {
		binds = append(binds, asTimestamp.GetId())
		binds = append(binds, asTimestamp.GetTimestampTwo().AsTime().Format(time.RFC3339))
		binds = append(binds, asTimestamp.GetTimestamp().AsTime().Format(time.RFC3339))
		bindsStrs = append(bindsStrs, "(?,?,?)")
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "as_timestamp" ("id","timestamp_two","timestamp") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of AsTimestamps matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteAsTimestampRepository) Read(ctx context.Context, expr expressions.Expression) ([]*AsTimestamp, error) {
	query := `SELECT "id","timestamp_two","timestamp"
		FROM "as_timestamp"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteAsTimestamp(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*AsTimestamp
	for rows.Next() {
		asTimestamp := &AsTimestamp_builder{}
		var timestampTwoTimeStr string
		var timestampTimeStr string

		if err = rows.Scan(&asTimestamp.Id, &timestampTwoTimeStr, &timestampTimeStr); err != nil {
			return nil, err
		}

		timestampTwoTime, err := time.Parse(time.RFC3339, timestampTwoTimeStr)
		if err != nil {
			return nil, err
		}
		asTimestamp.TimestampTwo = timestamppb.New(timestampTwoTime)

		timestampTime, err := time.Parse(time.RFC3339, timestampTimeStr)
		if err != nil {
			return nil, err
		}
		asTimestamp.Timestamp = timestamppb.New(timestampTime)

		found = append(found, asTimestamp.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing AsTimestamps based on the defined unique identifiers.
func (repo *SQLiteAsTimestampRepository) Update(ctx context.Context, toUpdate []*AsTimestamp) ([]*AsTimestamp, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "as_timestamp" SET "timestamp_two" = ?,"timestamp" = ? WHERE "id" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, asTimestamp := range toUpdate {
		_, err = stmt.ExecContext(ctx, asTimestamp.GetTimestampTwo().AsTime().Format(time.RFC3339), asTimestamp.GetTimestamp().AsTime().Format(time.RFC3339), asTimestamp.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes AsTimestamps based on the defined unique identifiers
func (repo *SQLiteAsTimestampRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "as_timestamp"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteAsTimestamp(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteAsTimestampColumnNameByFieldID = map[expressions.ID]string{
	AsTimestamp_Id_Field:           "id",
	AsTimestamp_TimestampTwo_Field: "timestamp_two",
	AsTimestamp_Timestamp_Field:    "timestamp",
}

func whereClauseFromExpressionForSQLiteAsTimestamp(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteAsTimestamp(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteAsTimestamp(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteAsTimestamp(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteAsTimestamp(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteAsTimestamp(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteAsTimestamp(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteAsTimestamp(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validAsTimestampFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteAsTimestampColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"as_timestamp"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}
