// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/as-timestamp-field/test.proto

/*
Package as_timestamp_field is a repository.

PgSQL implementation.
*/

package as_timestamp_field

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"google.golang.org/protobuf/types/known/timestamppb"
	pgxstdlib "github.com/jackc/pgx/v5/stdlib"
	"github.com/samlitowitz/expressions"
)

// InMemoryAsTimestampRepository is an in memory implementation of the AsTimestampRepository interface.
type PgSQLAsTimestampRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemoryAsTimestampRepository to be used.
func NewPgSQLAsTimestampRepository(db *sql.DB) (*PgSQLAsTimestampRepository, error) {
	_, ok := db.Driver().(*pgxstdlib.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *github.com/jackc/pgx/v5/stdlib/Driver")
	}
	return &PgSQLAsTimestampRepository{
		db: db,
	}, nil
}

// Create creates new AsTimestamps.
// Successfully created AsTimestamps are returned along with any errors that may have occurred.
func (repo *PgSQLAsTimestampRepository) Create(ctx context.Context, toCreate []*AsTimestamp) ([]*AsTimestamp, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	bindsIdx := 1
	for _, asTimestamp := range toCreate {
		binds = append(binds, asTimestamp.GetId())
		binds = append(binds, asTimestamp.GetTimestampTwo().AsTime())
		binds = append(binds, asTimestamp.GetTimestamp().AsTime())
		bindsStrs = append(bindsStrs, fmt.Sprintf("($%d, $%d, $%d)", bindsIdx+0, bindsIdx+1, bindsIdx+2))
		bindsIdx += 3
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "as_timestamp" ("id","timestamp_two","timestamp") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of AsTimestamps matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *PgSQLAsTimestampRepository) Read(ctx context.Context, expr expressions.Expression) ([]*AsTimestamp, error) {
	query := `SELECT "id","timestamp_two","timestamp"
		FROM "as_timestamp"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLAsTimestamp(expr, 1)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*AsTimestamp
	for rows.Next() {
		asTimestamp := &AsTimestamp_builder{}
		timestampTwoTime := &pgtype.Timestamp{}
		timestampTime := &pgtype.Timestamp{}

		if err = rows.Scan(&asTimestamp.Id, &timestampTwoTime, &timestampTime); err != nil {
			return nil, err
		}
		asTimestamp.TimestampTwo = timestamppb.New(timestampTwoTime.Time)
		asTimestamp.Timestamp = timestamppb.New(timestampTime.Time)

		found = append(found, asTimestamp.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing AsTimestamps based on the defined unique identifiers.
func (repo *PgSQLAsTimestampRepository) Update(ctx context.Context, toUpdate []*AsTimestamp) ([]*AsTimestamp, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "as_timestamp" SET "timestamp_two" = $1,"timestamp" = $2 WHERE "id" = $3`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, asTimestamp := range toUpdate {
		_, err = stmt.ExecContext(ctx, asTimestamp.GetTimestampTwo().AsTime(), asTimestamp.GetTimestamp().AsTime(), asTimestamp.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes AsTimestamps based on the defined unique identifiers
func (repo *PgSQLAsTimestampRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "as_timestamp"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLAsTimestamp(expr, 1)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var pgsqlAsTimestampColumnNameByFieldID = map[expressions.ID]string{
	AsTimestamp_Id_Field:           "id",
	AsTimestamp_TimestampTwo_Field: "timestamp_two",
	AsTimestamp_Timestamp_Field:    "timestamp",
}

func whereClauseFromExpressionForPgSQLAsTimestamp(expr expressions.Expression, paramIdx int) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLAsTimestamp(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLAsTimestamp(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLAsTimestamp(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLAsTimestamp(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForPgSQLAsTimestamp(expr.Operand(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLAsTimestamp(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLAsTimestamp(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validAsTimestampFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := pgsqlAsTimestampColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"as_timestamp"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return fmt.Sprintf("$%d", paramIdx), []any{expr.Value()}, nil
	case expressions.Timestamp:
		return fmt.Sprintf("$%d", paramIdx), []any{time.Time(expr)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}
