// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: test-cases/as-timestamp-field/test.proto

package as_timestamp_field

import (
	_ "github.com/samlitowitz/protoc-gen-crud/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AsTimestamp struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id           int32                  `protobuf:"varint,1,opt,name=id,proto3"`
	xxx_hidden_Timestamp    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3"`
	xxx_hidden_TimestampTwo *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp_two,json=timestampTwo,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AsTimestamp) Reset() {
	*x = AsTimestamp{}
	mi := &file_test_cases_as_timestamp_field_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AsTimestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsTimestamp) ProtoMessage() {}

func (x *AsTimestamp) ProtoReflect() protoreflect.Message {
	mi := &file_test_cases_as_timestamp_field_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AsTimestamp) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *AsTimestamp) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *AsTimestamp) GetTimestampTwo() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_TimestampTwo
	}
	return nil
}

func (x *AsTimestamp) SetId(v int32) {
	x.xxx_hidden_Id = v
}

func (x *AsTimestamp) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *AsTimestamp) SetTimestampTwo(v *timestamppb.Timestamp) {
	x.xxx_hidden_TimestampTwo = v
}

func (x *AsTimestamp) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *AsTimestamp) HasTimestampTwo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TimestampTwo != nil
}

func (x *AsTimestamp) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *AsTimestamp) ClearTimestampTwo() {
	x.xxx_hidden_TimestampTwo = nil
}

type AsTimestamp_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id           int32
	Timestamp    *timestamppb.Timestamp
	TimestampTwo *timestamppb.Timestamp
}

func (b0 AsTimestamp_builder) Build() *AsTimestamp {
	m0 := &AsTimestamp{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_TimestampTwo = b.TimestampTwo
	return m0
}

var File_test_cases_as_timestamp_field_test_proto protoreflect.FileDescriptor

const file_test_cases_as_timestamp_field_test_proto_rawDesc = "" +
	"\n" +
	"(test-cases/as-timestamp-field/test.proto\x12-protoc_gen_crud.test_cases.as_timestamp_field\x1a\x1coptions/v1/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x01\n" +
	"\vAsTimestamp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12@\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xfa\xff\x1f\x02 \x01R\ttimestamp\x12G\n" +
	"\rtimestamp_two\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xfa\xff\x1f\x02 \x01R\ftimestampTwo:\f\xfa\xff\x1f\b\n" +
	"\x02\x01\x02\x1a\x02idB\xc6\x02\n" +
	"1com.protoc_gen_crud.test_cases.as_timestamp_fieldB\tTestProtoP\x01ZDgithub.com/samlitowitz/protoc-gen-crud/test-cases/as-timestamp-field\xa2\x02\x03PTA\xaa\x02(ProtocGenCrud.TestCases.AsTimestampField\xca\x02(ProtocGenCrud\\TestCases\\AsTimestampField\xe2\x024ProtocGenCrud\\TestCases\\AsTimestampField\\GPBMetadata\xea\x02*ProtocGenCrud::TestCases::AsTimestampFieldb\x06proto3"

var file_test_cases_as_timestamp_field_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_cases_as_timestamp_field_test_proto_goTypes = []any{
	(*AsTimestamp)(nil),           // 0: protoc_gen_crud.test_cases.as_timestamp_field.AsTimestamp
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_test_cases_as_timestamp_field_test_proto_depIdxs = []int32{
	1, // 0: protoc_gen_crud.test_cases.as_timestamp_field.AsTimestamp.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: protoc_gen_crud.test_cases.as_timestamp_field.AsTimestamp.timestamp_two:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_test_cases_as_timestamp_field_test_proto_init() }
func file_test_cases_as_timestamp_field_test_proto_init() {
	if File_test_cases_as_timestamp_field_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_cases_as_timestamp_field_test_proto_rawDesc), len(file_test_cases_as_timestamp_field_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_cases_as_timestamp_field_test_proto_goTypes,
		DependencyIndexes: file_test_cases_as_timestamp_field_test_proto_depIdxs,
		MessageInfos:      file_test_cases_as_timestamp_field_test_proto_msgTypes,
	}.Build()
	File_test_cases_as_timestamp_field_test_proto = out.File
	file_test_cases_as_timestamp_field_test_proto_goTypes = nil
	file_test_cases_as_timestamp_field_test_proto_depIdxs = nil
}
