// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: protoc-gen-crud/examples/many-to-many-relationship/user.proto

/*
Package many_to_many_relationship is a repository.

It provides an interface to implement.
*/

package many_to_many_relationship
