// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v7.35.0
// source: test-cases/with-no-implementations-set/test.proto

package with_no_implementations_set

import (
	_ "github.com/samlitowitz/protoc-gen-crud/options/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoImplementations struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoImplementations) Reset() {
	*x = NoImplementations{}
	mi := &file_test_cases_with_no_implementations_set_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoImplementations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoImplementations) ProtoMessage() {}

func (x *NoImplementations) ProtoReflect() protoreflect.Message {
	mi := &file_test_cases_with_no_implementations_set_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NoImplementations) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *NoImplementations) SetId(v string) {
	x.xxx_hidden_Id = v
}

type NoImplementations_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 NoImplementations_builder) Build() *NoImplementations {
	m0 := &NoImplementations{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

type EmptyImplementations struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyImplementations) Reset() {
	*x = EmptyImplementations{}
	mi := &file_test_cases_with_no_implementations_set_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyImplementations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyImplementations) ProtoMessage() {}

func (x *EmptyImplementations) ProtoReflect() protoreflect.Message {
	mi := &file_test_cases_with_no_implementations_set_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EmptyImplementations) GetId() string {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return ""
}

func (x *EmptyImplementations) SetId(v string) {
	x.xxx_hidden_Id = v
}

type EmptyImplementations_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id string
}

func (b0 EmptyImplementations_builder) Build() *EmptyImplementations {
	m0 := &EmptyImplementations{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Id = b.Id
	return m0
}

var File_test_cases_with_no_implementations_set_test_proto protoreflect.FileDescriptor

var file_test_cases_with_no_implementations_set_test_proto_rawDesc = []byte{
	0x0a, 0x31, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x63, 0x61, 0x73, 0x65, 0x73, 0x2f, 0x77, 0x69, 0x74,
	0x68, 0x2d, 0x6e, 0x6f, 0x2d, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x73, 0x65, 0x74, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x36, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x5f, 0x67, 0x65, 0x6e, 0x5f,
	0x63, 0x72, 0x75, 0x64, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x63, 0x61, 0x73, 0x65, 0x73, 0x2e,
	0x77, 0x69, 0x74, 0x68, 0x5f, 0x6e, 0x6f, 0x5f, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f, 0x73, 0x65, 0x74, 0x1a, 0x1c, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x11, 0x4e, 0x6f, 0x49,
	0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x3a, 0x08,
	0xfa, 0xff, 0x1f, 0x04, 0x1a, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x49, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x3a, 0x08, 0xfa, 0xff, 0x1f, 0x04, 0x1a, 0x02, 0x69, 0x64, 0x42, 0x4f, 0x5a, 0x4d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x6d, 0x6c, 0x69, 0x74, 0x6f,
	0x77, 0x69, 0x74, 0x7a, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d,
	0x63, 0x72, 0x75, 0x64, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x2d, 0x63, 0x61, 0x73, 0x65, 0x73, 0x2f,
	0x77, 0x69, 0x74, 0x68, 0x2d, 0x6e, 0x6f, 0x2d, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2d, 0x73, 0x65, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var file_test_cases_with_no_implementations_set_test_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_cases_with_no_implementations_set_test_proto_goTypes = []any{
	(*NoImplementations)(nil),    // 0: protoc_gen_crud.test_cases.with_no_implementations_set.NoImplementations
	(*EmptyImplementations)(nil), // 1: protoc_gen_crud.test_cases.with_no_implementations_set.EmptyImplementations
}
var file_test_cases_with_no_implementations_set_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_cases_with_no_implementations_set_test_proto_init() }
func file_test_cases_with_no_implementations_set_test_proto_init() {
	if File_test_cases_with_no_implementations_set_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_cases_with_no_implementations_set_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_cases_with_no_implementations_set_test_proto_goTypes,
		DependencyIndexes: file_test_cases_with_no_implementations_set_test_proto_depIdxs,
		MessageInfos:      file_test_cases_with_no_implementations_set_test_proto_msgTypes,
	}.Build()
	File_test_cases_with_no_implementations_set_test_proto = out.File
	file_test_cases_with_no_implementations_set_test_proto_rawDesc = nil
	file_test_cases_with_no_implementations_set_test_proto_goTypes = nil
	file_test_cases_with_no_implementations_set_test_proto_depIdxs = nil
}
