// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/with-no-implementations-set/test.proto

/*
Package with_no_implementations_set is a repository.

It provides an interface to implement.
*/

package with_no_implementations_set

import (
	"context"

	"github.com/samlitowitz/expressions"
)

// These constants are used to specify fields in expressions
const (
	NoImplementations_Id_Field expressions.ID = "797d63ea2f89a3c24a9d08940f2f75386cb473a3f95ee80027efd5ecc9c19961"
)

var validNoImplementationsFields = map[expressions.ID]struct{}{
	NoImplementations_Id_Field: struct{}{},
}

type NoImplementationsRepository interface {
	// Create creates new NoImplementationss.
	// Successfully created NoImplementationss are returned along with any errors that may have occurred.
	Create(context.Context, []*NoImplementations) ([]*NoImplementations, error)

	// Read returns a set of NoImplementationss matching the provided criteria
	Read(context.Context, expressions.Expression) ([]*NoImplementations, error)

	// Update modifies existing NoImplementationss based on the defined unique identifiers.
	// Successfully modified NoImplementationss are returned along with any errors that may have occurred.
	Update(context.Context, []*NoImplementations) ([]*NoImplementations, error)

	// Delete deletes NoImplementationss matching the provided criteria
	Delete(context.Context, expressions.Expression) error
}

// These constants are used to specify fields in expressions
const (
	EmptyImplementations_Id_Field expressions.ID = "fb3329e07bda1a29436983e60bb26952aa082925c9dfe94c1b4b7d16293e69d6"
)

var validEmptyImplementationsFields = map[expressions.ID]struct{}{
	EmptyImplementations_Id_Field: struct{}{},
}

type EmptyImplementationsRepository interface {
	// Create creates new EmptyImplementationss.
	// Successfully created EmptyImplementationss are returned along with any errors that may have occurred.
	Create(context.Context, []*EmptyImplementations) ([]*EmptyImplementations, error)

	// Read returns a set of EmptyImplementationss matching the provided criteria
	Read(context.Context, expressions.Expression) ([]*EmptyImplementations, error)

	// Update modifies existing EmptyImplementationss based on the defined unique identifiers.
	// Successfully modified EmptyImplementationss are returned along with any errors that may have occurred.
	Update(context.Context, []*EmptyImplementations) ([]*EmptyImplementations, error)

	// Delete deletes EmptyImplementationss matching the provided criteria
	Delete(context.Context, expressions.Expression) error
}
