// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: protoc-gen-crud/examples/spacer/entity.proto

/*
Package spacer is a repository.

SQLite implementation.
*/

package spacer

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/mennanov/fmutils"
	"github.com/samlitowitz/protoc-gen-crud/expressions"
	"google.golang.org/protobuf/types/known/fieldmaskpb"
	"modernc.org/sqlite"
)

// InMemoryEntityRepository is an in memory implementation of the EntityRepository interface.
type SQLiteEntityRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemoryEntityRepository to be used.
func NewSQLiteEntityRepository(db *sql.DB) (*SQLiteEntityRepository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteEntityRepository{
		db: db,
	}, nil
}

// Create creates new Entitys.
// Successfully created Entitys are returned along with any errors that may have occurred.
func (repo *SQLiteEntityRepository) Create(ctx context.Context, toCreate []*Entity) ([]*Entity, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()
	noMaskBinds := []any{}
	noMaskBindsStrs := []string{}
	for _, entity := range toCreate {
		if entity.FieldMask == nil {
			noMaskBinds = append(noMaskBinds, entity.GetId())
			noMaskBinds = append(noMaskBinds, entity.GetDescription())
			noMaskBindsStrs = append(noMaskBindsStrs, "(?,?)")
			continue
		}
		valuesByColName, err := sqliteEntityGetCreateValuesByColumnName(entity, entity.FieldMask)
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var cols []string
		var params []string
		for colName, value := range valuesByColName {
			cols = append(cols, "\""+colName+"\"")
			params = append(params, "?")
			binds = append(binds, value)
		}
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				"INSERT INTO \"entity\" (%s) VALUES \n (%s)",
				strings.Join(cols, ", "),
				strings.Join(params, ", "),
			),
			binds...,
		)
		if err != nil {
			return nil, err
		}
	}
	if len(noMaskBinds) > 0 {
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				"INSERT INTO \"entity\" (\"id\",\"description\") VALUES \n %s",
				strings.Join(noMaskBindsStrs, ",\n"),
			),
			noMaskBinds...,
		)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of Entitys matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteEntityRepository) Read(ctx context.Context, expr expressions.Expression) ([]*Entity, error) {
	query := "SELECT \"id\",\"description\" FROM \"entity\""
	clauses, binds, err := whereClauseFromExpressionForEntity(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*Entity
	for rows.Next() {
		entity := &Entity{}
		if err = rows.Scan(&entity.Id, &entity.Description); err != nil {
			return nil, err
		}
		found = append(found, entity)
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing Entitys based on the defined unique identifiers.
func (repo *SQLiteEntityRepository) Update(ctx context.Context, toUpdate []*Entity) ([]*Entity, error) {

	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		"UPDATE \"entity\" SET \"description\" = ?,\"tags_id\" = ? WHERE \"id\" = ?",
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()
	for _, entity := range toUpdate {
		if entity.FieldMask == nil {
			_, err = stmt.ExecContext(ctx, entity.GetDescription(), entity.GetTags().GetId(), entity.GetId())
			if err != nil {
				return nil, err
			}
			continue
		}
		valuesByColName, err := sqliteEntityGetUpdateValuesByColumnName(entity, entity.FieldMask)
		if err != nil {
			return nil, err
		}
		if len(valuesByColName) == 0 {
			continue
		}
		var binds []any
		var setStmts []string
		for colName, value := range valuesByColName {
			setStmts = append(setStmts, fmt.Sprintf("\"%s\" = ?", colName))
			binds = append(binds, value)
		}
		_, err = tx.ExecContext(
			ctx,
			fmt.Sprintf(
				"UPDATE \"entity\" SET %s WHERE \"id\" = ?",
				strings.Join(setStmts, ", "),
			),
			append(
				binds,
				entity.GetId(),
			)...,
		)
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil

}

// Delete deletes Entitys based on the defined unique identifiers
func (repo *SQLiteEntityRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := "DELETE FROM \"entity\""
	clauses, binds, err := whereClauseFromExpressionForEntity(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteEntityColumnNameByFieldID = map[expressions.FieldID]string{
	Entity_Description_Field: "description",
	Entity_FieldMask_Field:   "field_mask",
	Entity_Id_Field:          "id",
	Entity_Tags_Id_Field:     "tags",
}

func whereClauseFromExpressionForEntity(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForEntity(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForEntity(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForEntity(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForEntity(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForEntity(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equal:
		left, leftBinds, err := whereClauseFromExpressionForEntity(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForEntity(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validEntityFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteEntityColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf("\"entity\".\"%s\"", colName), nil, nil

	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

func sqliteEntityGetCreateValuesByColumnName(def *Entity, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	entity := &Entity{}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; ok {
		valuesByColumnName["id"] = def.GetId()
	} else {
		valuesByColumnName["id"] = entity.GetId()
	}
	if _, ok := nestedMask["description"]; ok {
		valuesByColumnName["description"] = def.GetDescription()
	} else {
		valuesByColumnName["description"] = entity.GetDescription()
	}
	return valuesByColumnName, nil
}
func sqliteEntityGetUpdateValuesByColumnName(def *Entity, fieldMask *fieldmaskpb.FieldMask) (map[string]any, error) {
	if fieldMask == nil {
		return nil, fmt.Errorf("no field mask provided")
	}
	valuesByColumnName := make(map[string]any, 0)
	nestedMask := fmutils.NestedMaskFromPaths(fieldMask.Paths)
	if _, ok := nestedMask["id"]; ok {
		valuesByColumnName["id"] = def.GetId()
	}
	if _, ok := nestedMask["description"]; ok {
		valuesByColumnName["description"] = def.GetDescription()
	}
	return valuesByColumnName, nil
}
