// Code generated by "stringer -type=Typ"; DO NOT EDIT.

package relationship

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MANY_TO_MANY-0]
	_ = x[MANY_TO_ONE-1]
	_ = x[ONE_TO_MANY-2]
	_ = x[ONE_TO_ONE-3]
}

const _Typ_name = "MANY_TO_MANYMANY_TO_ONEONE_TO_MANYONE_TO_ONE"

var _Typ_index = [...]uint8{0, 12, 23, 34, 44}

func (i Typ) String() string {
	if i < 0 || i >= Typ(len(_Typ_index)-1) {
		return "Typ(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Typ_name[_Typ_index[i]:_Typ_index[i+1]]
}
