// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/inline-field/test.proto

/*
Package inline_field is a repository.

SQLite implementation.
*/

package inline_field

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
	"modernc.org/sqlite"
	"github.com/samlitowitz/expressions"
)

// InMemoryInlineTimestampRepository is an in memory implementation of the InlineTimestampRepository interface.
type SQLiteInlineTimestampRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemoryInlineTimestampRepository to be used.
func NewSQLiteInlineTimestampRepository(db *sql.DB) (*SQLiteInlineTimestampRepository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteInlineTimestampRepository{
		db: db,
	}, nil
}

// Create creates new InlineTimestamps.
// Successfully created InlineTimestamps are returned along with any errors that may have occurred.
func (repo *SQLiteInlineTimestampRepository) Create(ctx context.Context, toCreate []*InlineTimestamp) ([]*InlineTimestamp, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	for _, inlineTimestamp := range toCreate {
		binds = append(binds, inlineTimestamp.GetId())
		binds = append(binds, inlineTimestamp.GetTimestamp().GetSeconds())
		binds = append(binds, inlineTimestamp.GetTimestamp().GetNanos())
		bindsStrs = append(bindsStrs, "(?,?,?)")
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "inline_timestamp" ("id","timestamp_seconds","timestamp_nanos") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of InlineTimestamps matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteInlineTimestampRepository) Read(ctx context.Context, expr expressions.Expression) ([]*InlineTimestamp, error) {
	query := `SELECT "id","timestamp_seconds","timestamp_nanos"
		FROM "inline_timestamp"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteInlineTimestamp(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*InlineTimestamp
	for rows.Next() {
		inlineTimestamp := &InlineTimestamp_builder{

			Timestamp: &timestamppb.Timestamp{},
		}

		if err = rows.Scan(&inlineTimestamp.Id, &inlineTimestamp.Timestamp.Seconds, &inlineTimestamp.Timestamp.Nanos); err != nil {
			return nil, err
		}

		found = append(found, inlineTimestamp.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing InlineTimestamps based on the defined unique identifiers.
func (repo *SQLiteInlineTimestampRepository) Update(ctx context.Context, toUpdate []*InlineTimestamp) ([]*InlineTimestamp, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "inline_timestamp" SET "timestamp_seconds" = ?,"timestamp_nanos" = ? WHERE "id" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, inlineTimestamp := range toUpdate {
		_, err = stmt.ExecContext(ctx, inlineTimestamp.GetTimestamp().GetSeconds(), inlineTimestamp.GetTimestamp().GetNanos(), inlineTimestamp.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes InlineTimestamps based on the defined unique identifiers
func (repo *SQLiteInlineTimestampRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "inline_timestamp"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteInlineTimestamp(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteInlineTimestampColumnNameByFieldID = map[expressions.ID]string{
	InlineTimestamp_Id_Field:                "id",
	InlineTimestamp_Timestamp_Seconds_Field: "timestamp_seconds",
	InlineTimestamp_Timestamp_Nanos_Field:   "timestamp_nanos",
}

func whereClauseFromExpressionForSQLiteInlineTimestamp(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteInlineTimestamp(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteInlineTimestamp(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteInlineTimestamp(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteInlineTimestamp(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteInlineTimestamp(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteInlineTimestamp(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteInlineTimestamp(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validInlineTimestampFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteInlineTimestampColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"inline_timestamp"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}
