// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/inline-field/test.proto

/*
Package inline_field is a repository.

It provides an interface to implement.
*/

package inline_field

import (
	"context"

	"github.com/samlitowitz/expressions"
)

// These constants are used to specify fields in expressions
const (
	InlineTimestamp_Id_Field                expressions.ID = "eb592ac91a491c9a3c0a3e77f69bbd70e33faed2bfc32f7b568e35129d92eb66"
	InlineTimestamp_Timestamp_Seconds_Field expressions.ID = "502034448ba70b2013510421704746c0b923bf243aeb6ff20dcce18ec0779bd6"
	InlineTimestamp_Timestamp_Nanos_Field   expressions.ID = "145496bd395bb9a358b1bcafcdc8a0d00df1737729f39ab73c9d0313c7abf2e0"
)

var validInlineTimestampFields = map[expressions.ID]struct{}{
	InlineTimestamp_Id_Field:                struct{}{},
	InlineTimestamp_Timestamp_Seconds_Field: struct{}{},
	InlineTimestamp_Timestamp_Nanos_Field:   struct{}{},
}

type InlineTimestampRepository interface {
	// Create creates new InlineTimestamps.
	// Successfully created InlineTimestamps are returned along with any errors that may have occurred.
	Create(context.Context, []*InlineTimestamp) ([]*InlineTimestamp, error)

	// Read returns a set of InlineTimestamps matching the provided criteria
	Read(context.Context, expressions.Expression) ([]*InlineTimestamp, error)

	// Update modifies existing InlineTimestamps based on the defined unique identifiers.
	// Successfully modified InlineTimestamps are returned along with any errors that may have occurred.
	Update(context.Context, []*InlineTimestamp) ([]*InlineTimestamp, error)

	// Delete deletes InlineTimestamps matching the provided criteria
	Delete(context.Context, expressions.Expression) error
}
