// REFURL: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-grpc-gateway/internal/gengateway/template.go
package gen_go_crud

import (
	"bytes"
	"text/template"

	"github.com/samlitowitz/protoc-gen-crud/internal/casing"
	"github.com/samlitowitz/protoc-gen-crud/internal/descriptor"
)

type param struct {
	*descriptor.File
	Imports []descriptor.GoPackage
}

type crud struct {
	*descriptor.CRUD
	Registry *descriptor.Registry
}

func applyTemplate(p param, reg *descriptor.Registry) (string, error) {
	w := bytes.NewBuffer(nil)
	if err := headerTemplate.Execute(w, p); err != nil {
		return "", err
	}

	for _, msg := range p.Messages {
		msgName := casing.Camel(*msg.Name)
		msg.Name = &msgName
	}
	for _, msg := range p.Messages {
		if msg.CRUD == nil {
			continue
		}
		if err := repositoryTemplate.Execute(w, &crud{CRUD: msg.CRUD, Registry: reg}); err != nil {
			return "", nil
		}
	}

	return w.String(), nil
}

var (
	headerTemplate = template.Must(template.New("header").Parse(`
// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: {{.GetName}}

/*
Package {{.GoPkg.Name}} is a repository.

It provides an interface to implement and some implementations of the interface.
*/

package {{.GoPkg.Name}}
{{if .Imports}}
import (
	{{range $i := .Imports}}{{if $i.Standard}}{{$i | printf "%s\n"}}{{end}}{{end}}

	{{range $i := .Imports}}{{if not $i.Standard}}{{$i | printf "%s\n"}}{{end}}{{end}}
)
{{end}}
`))

	repositoryTemplate = template.Must(template.New("repository").Parse(`
{{template "repository-interface" .}}
`))

	funcMap template.FuncMap = map[string]interface{}{
		"camelIdentifier": casing.CamelIdentifier,
	}

	_ = template.Must(repositoryTemplate.New("repository-interface").Funcs(funcMap).Parse(`

type {{.Message.GoType .Message.File.GoPkg.Path}}Repository interface {
	/*
		{{printf "%#v" (.Message.CRUD)}}
	*/
	{{if .Message.CRUD.Create}}
	func Create([]*{{.Message.GoType .Message.File.GoPkg.Path}}) ([]*{{.Message.GoType .Message.File.GoPkg.Path}}, error)
	{{end}}
}
`))
)

//type {{.Message.GoType}}Repository interface {
//{{if .Message.CRUD.Create}}
//func Create([]*{{.Message.GoType}}) ([]*{{.Message.GoType}}, error)
//{{end}}
//{{if .Message.CRUD.Read}
//func Read([]*{{.Message.GoType}}) ([]*{{.Message.GoType}}, error)
//{{end}}
//{{if .Message.Update}}
//func Update([]*{{.Message.GoType}}) ([]*{{.Message.GoType}}, error)
//{{end}}
//{{if .Message.Delete}}
//func Delete([]*{{.Message.GoType}}) error
//{{end}}
//}
