// REFURL: https://github.com/grpc-ecosystem/grpc-gateway/blob/main/protoc-gen-grpc-gateway/internal/gengateway/template.go
package gen_go_crud

import (
	"bytes"
	"text/template"

	"github.com/samlitowitz/protoc-gen-crud/internal/casing"
	"github.com/samlitowitz/protoc-gen-crud/internal/descriptor"
)

type param struct {
	*descriptor.File
	Imports []descriptor.GoPackage
}

type crud struct {
	*descriptor.CRUD
	Registry *descriptor.Registry
}

func applyTemplate(p param, reg *descriptor.Registry) (string, error) {
	w := bytes.NewBuffer(nil)
	if err := headerTemplate.Execute(w, p); err != nil {
		return "", err
	}

	for _, msg := range p.Messages {
		msgName := casing.Camel(*msg.Name)
		msg.Name = &msgName
	}
	for _, def := range p.CRUDs {
		if err := repositoryTemplate.Execute(w, &crud{CRUD: def, Registry: reg}); err != nil {
			return "", nil
		}
	}

	return w.String(), nil
}

var (
	headerTemplate = template.Must(template.New("header").Parse(`
// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: {{.GetName}}

/*
Package {{.GoPkg.Name}} is a repository.

It provides an interface to implement and some implementations of the interface.
*/

package {{.GoPkg.Name}}
{{if .Imports}}
import (
	{{range $i := .Imports}}{{if $i.Standard}}{{$i | printf "%s\n"}}{{end}}{{end}}

	{{range $i := .Imports}}{{if not $i.Standard}}{{$i | printf "%s\n"}}{{end}}{{end}}
)
{{end}}
`))

	repositoryTemplate = template.Must(template.New("repository").Parse(`
{{template "repository-interface" .}}
{{if .CRUD.InMemory}}
	{{template "repository-in-memory" .}}
{{end}}
`))

	funcMap template.FuncMap = map[string]interface{}{
		"camelIdentifier": casing.CamelIdentifier,
	}

	_ = template.Must(repositoryTemplate.New("repository-interface").Funcs(funcMap).Parse(`

type {{.CRUD.Name}}Repository interface {
	{{if .CRUD.Create}}
	// TODO: Add Comment
	func Create([]*{{.CRUD.GoType .CRUD.File.GoPkg.Path}}) ([]*{{.CRUD.GoType .CRUD.File.GoPkg.Path}}, error)
	{{end}}
	{{if .CRUD.Read}}
	// TODO: Add Comment
	// Read is incomplete and it should be considered unstable
	// Use where clauses
	func Read() ([]*{{.CRUD.GoType .CRUD.File.GoPkg.Path}}, error)
	{{end}}
	{{if .CRUD.Update}}
	// TODO: Add Comment
	func Update([]*{{.CRUD.GoType .CRUD.File.GoPkg.Path}}) ([]*{{.CRUD.GoType .CRUD.File.GoPkg.Path}}, error)
	{{end}}
	{{if .CRUD.Delete}}
	// TODO: Add Comment
	// Delete is incomplete and it should be considered unstable
	// Use where clauses
	func Delete([]*{{.CRUD.GoType .CRUD.File.GoPkg.Path}}) error
	{{end}}
}
`))
)
