// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/ignore-field/test.proto

/*
Package ignore_field is a repository.

It provides an interface to implement.
*/

package ignore_field

import (
	"context"

	"github.com/samlitowitz/expressions"
)

// These constants are used to specify fields in expressions
const (
	Test_Id_Field   expressions.ID = "163375fe204a82138db8fc6b9e48b42f1a407197b38602872842f225a814f93c"
	Test_Data_Field expressions.ID = "e392a99a384f5df4095302c6048af40bea44bc2a4f5885942c4af74128d0cabf"
)

var validTestFields = map[expressions.ID]struct{}{
	Test_Id_Field:   struct{}{},
	Test_Data_Field: struct{}{},
}

type TestRepository interface {
	// Create creates new Tests.
	// Successfully created Tests are returned along with any errors that may have occurred.
	Create(context.Context, []*Test) ([]*Test, error)

	// Read returns a set of Tests matching the provided criteria
	Read(context.Context, expressions.Expression) ([]*Test, error)

	// Update modifies existing Tests based on the defined unique identifiers.
	// Successfully modified Tests are returned along with any errors that may have occurred.
	Update(context.Context, []*Test) ([]*Test, error)

	// Delete deletes Tests matching the provided criteria
	Delete(context.Context, expressions.Expression) error
}
