// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/ignore-field/test.proto

/*
Package ignore_field is a repository.

SQLite implementation.
*/

package ignore_field

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"modernc.org/sqlite"
	"github.com/samlitowitz/expressions"
)

// InMemoryTestRepository is an in memory implementation of the TestRepository interface.
type SQLiteTestRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemoryTestRepository to be used.
func NewSQLiteTestRepository(db *sql.DB) (*SQLiteTestRepository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteTestRepository{
		db: db,
	}, nil
}

// Create creates new Tests.
// Successfully created Tests are returned along with any errors that may have occurred.
func (repo *SQLiteTestRepository) Create(ctx context.Context, toCreate []*Test) ([]*Test, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	for _, test := range toCreate {
		binds = append(binds, test.GetId())
		binds = append(binds, test.GetData())
		bindsStrs = append(bindsStrs, "(?,?)")
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "test" ("id","data") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of Tests matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteTestRepository) Read(ctx context.Context, expr expressions.Expression) ([]*Test, error) {
	query := `SELECT "id","data"
		FROM "test"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteTest(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*Test
	for rows.Next() {
		test := &Test_builder{}

		if err = rows.Scan(&test.Id, &test.Data); err != nil {
			return nil, err
		}

		found = append(found, test.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing Tests based on the defined unique identifiers.
func (repo *SQLiteTestRepository) Update(ctx context.Context, toUpdate []*Test) ([]*Test, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "test" SET "data" = ? WHERE "id" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, test := range toUpdate {
		_, err = stmt.ExecContext(ctx, test.GetData(), test.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes Tests based on the defined unique identifiers
func (repo *SQLiteTestRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "test"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteTest(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteTestColumnNameByFieldID = map[expressions.ID]string{
	Test_Id_Field:   "id",
	Test_Data_Field: "data",
}

func whereClauseFromExpressionForSQLiteTest(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteTest(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteTest(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteTest(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteTest(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteTest(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteTest(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteTest(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validTestFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteTestColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"test"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}
