// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: protoc-gen-crud/examples/simple/user.proto

/*
Package simple is a repository.

It provides an interface to implement.
*/

package simple

import (
	"context"

	"github.com/samlitowitz/protoc-gen-crud/expressions"
)

const (
	User_Id_Field       expressions.FieldID = "441df8206d64f0e4cf6ad874026ceab109b6b0d2262387c2273ed1d80973589f"
	User_Password_Field expressions.FieldID = "fcf0b45269d1e8a2cc0c5c9d3d6013283791fb304e4022200c908dfb41da4019"
	User_Username_Field expressions.FieldID = "3a893c049a89f5736a021eebc001470079160c4bb5e213e8913b73108d67ba6a"
)

var validUserFields = map[expressions.FieldID]struct{}{
	User_Id_Field:       struct{}{},
	User_Password_Field: struct{}{},
	User_Username_Field: struct{}{},
}

type UserRepository interface {
	// Create creates new Users.
	// Successfully created Users are returned along with any errors that may have occurred.
	Create(context.Context, []*User) ([]*User, error)

	// Read returns a set of Users matching the provided criteria
	// Read is incomplete and it should be considered unstable
	Read(context.Context, expressions.Expression) ([]*User, error)

	// Update modifies existing Users based on the defined unique identifiers.
	// Successfully modified Users are returned along with any errors that may have occurred.
	Update(context.Context, []*User) ([]*User, error)

	// Delete deletes Users matching the provided criteria
	// Delete is incomplete and it should be considered unstable
	Delete(context.Context, expressions.Expression) error
}
