// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: protoc-gen-crud/examples/simple/user.proto

/*
Package simple is a repository.

SQLite implementation.
*/

package simple

// InMemoryUserRepository is an in memory implementation of the UserRepository interface.
type SQLiteUserRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemoryUserRepository to be used.
func NewSQLiteUserRepository(db *sql.DB) (*SQLiteUserRepository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteUserRepository{
		db: db,
	}, nil
}
