// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
<<<<<<< HEAD:options/crud.pb.go
// 	protoc-gen-go v1.36.0
// 	protoc        v7.35.0
// source: protoc-gen-crud/options/crud.proto
=======
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: options/v1/crud.proto
>>>>>>> 82cf231 (Initial commit, issue-1):options/v1/crud.pb.go

package optionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Implementations supported by `protoc-gen-crud`
type Implementation int32

const (
	Implementation_IMPLEMENTATION_UNSPECIFIED Implementation = 0 // Generate nothing via `protoc-gen-crud`
	Implementation_IMPLEMENTATION_SQLITE      Implementation = 1 // Generate SQLite SQL and Go code
	Implementation_IMPLEMENTATION_PGSQL       Implementation = 2 // Generate Postgres SQL and Go code
)

// Enum value maps for Implementation.
var (
	Implementation_name = map[int32]string{
		0: "IMPLEMENTATION_UNSPECIFIED",
		1: "IMPLEMENTATION_SQLITE",
		2: "IMPLEMENTATION_PGSQL",
	}
	Implementation_value = map[string]int32{
		"IMPLEMENTATION_UNSPECIFIED": 0,
		"IMPLEMENTATION_SQLITE":      1,
		"IMPLEMENTATION_PGSQL":       2,
	}
)

func (x Implementation) Enum() *Implementation {
	p := new(Implementation)
	*p = x
	return p
}

func (x Implementation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Implementation) Descriptor() protoreflect.EnumDescriptor {
	return file_options_v1_crud_proto_enumTypes[0].Descriptor()
}

func (Implementation) Type() protoreflect.EnumType {
	return &file_options_v1_crud_proto_enumTypes[0]
}

func (x Implementation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type FileOptions struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_options_v1_crud_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_crud_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type FileOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 FileOptions_builder) Build() *FileOptions {
	m0 := &FileOptions{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type MethodOptions struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_options_v1_crud_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_crud_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type MethodOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 MethodOptions_builder) Build() *MethodOptions {
	m0 := &MethodOptions{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type MessageOptions struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Implementations []Implementation       `protobuf:"varint,1,rep,packed,name=implementations,proto3,enum=options.v1.Implementation"`
	xxx_hidden_FieldMask       string                 `protobuf:"bytes,2,opt,name=fieldMask,proto3"`
	xxx_hidden_PrimaryKey      []string               `protobuf:"bytes,3,rep,name=primaryKey,proto3"`
	xxx_hidden_CreatedAt       string                 `protobuf:"bytes,4,opt,name=createdAt,proto3"`
	xxx_hidden_UpdatedAt       string                 `protobuf:"bytes,5,opt,name=updatedAt,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_options_v1_crud_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_crud_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MessageOptions) GetImplementations() []Implementation {
	if x != nil {
		return x.xxx_hidden_Implementations
	}
	return nil
}

func (x *MessageOptions) GetFieldMask() string {
	if x != nil {
		return x.xxx_hidden_FieldMask
	}
	return ""
}

func (x *MessageOptions) GetPrimaryKey() []string {
	if x != nil {
		return x.xxx_hidden_PrimaryKey
	}
	return nil
}

func (x *MessageOptions) GetCreatedAt() string {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return ""
}

func (x *MessageOptions) GetUpdatedAt() string {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return ""
}

func (x *MessageOptions) SetImplementations(v []Implementation) {
	x.xxx_hidden_Implementations = v
}

func (x *MessageOptions) SetFieldMask(v string) {
	x.xxx_hidden_FieldMask = v
}

func (x *MessageOptions) SetPrimaryKey(v []string) {
	x.xxx_hidden_PrimaryKey = v
}

func (x *MessageOptions) SetCreatedAt(v string) {
	x.xxx_hidden_CreatedAt = v
}

func (x *MessageOptions) SetUpdatedAt(v string) {
	x.xxx_hidden_UpdatedAt = v
}

type MessageOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Sets the implementations to generate for this message.
	Implementations []Implementation
	// Sets the property of this message to be used as the field mask.
	// The field mask is enables and is required for partial create and update support.
	// If set, the property must exist on the message and be of type `google.protobuf.FieldMask`.
	// If not set updates affect all message properties.
	FieldMask string
	// Sets the properties of this message to be used as primary key(s).
	// There must be at least one primary key defined.
	PrimaryKey []string
	// Sets the property of this message to be used to track when this message was created.
	// If set, the property must exist on the message and must have `asTimestamp` set to true.
	CreatedAt string
	// Sets the property of this message to be used to track when this message was created.
	// If set, the property must exist on the message and must have `asTimestamp` set to true.
	UpdatedAt string
}

func (b0 MessageOptions_builder) Build() *MessageOptions {
	m0 := &MessageOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Implementations = b.Implementations
	x.xxx_hidden_FieldMask = b.FieldMask
	x.xxx_hidden_PrimaryKey = b.PrimaryKey
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	return m0
}

type ServiceOptions struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_options_v1_crud_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_crud_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ServiceOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ServiceOptions_builder) Build() *ServiceOptions {
	m0 := &ServiceOptions{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// TODO: Document FieldOptions
type FieldOptions struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Relationship *Relationship          `protobuf:"bytes,1,opt,name=relationship,proto3"`
	xxx_hidden_Ignore       bool                   `protobuf:"varint,2,opt,name=ignore,proto3"`
	xxx_hidden_Inline       bool                   `protobuf:"varint,3,opt,name=inline,proto3"`
	xxx_hidden_AsTimestamp  bool                   `protobuf:"varint,4,opt,name=asTimestamp,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_options_v1_crud_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_options_v1_crud_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FieldOptions) GetRelationship() *Relationship {
	if x != nil {
		return x.xxx_hidden_Relationship
	}
	return nil
}

func (x *FieldOptions) GetIgnore() bool {
	if x != nil {
		return x.xxx_hidden_Ignore
	}
	return false
}

func (x *FieldOptions) GetInline() bool {
	if x != nil {
		return x.xxx_hidden_Inline
	}
	return false
}

func (x *FieldOptions) GetAsTimestamp() bool {
	if x != nil {
		return x.xxx_hidden_AsTimestamp
	}
	return false
}

func (x *FieldOptions) SetRelationship(v *Relationship) {
	x.xxx_hidden_Relationship = v
}

func (x *FieldOptions) SetIgnore(v bool) {
	x.xxx_hidden_Ignore = v
}

func (x *FieldOptions) SetInline(v bool) {
	x.xxx_hidden_Inline = v
}

func (x *FieldOptions) SetAsTimestamp(v bool) {
	x.xxx_hidden_AsTimestamp = v
}

func (x *FieldOptions) HasRelationship() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Relationship != nil
}

func (x *FieldOptions) ClearRelationship() {
	x.xxx_hidden_Relationship = nil
}

type FieldOptions_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Relationship *Relationship
	Ignore       bool
	Inline       bool
	AsTimestamp  bool
}

func (b0 FieldOptions_builder) Build() *FieldOptions {
	m0 := &FieldOptions{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Relationship = b.Relationship
	x.xxx_hidden_Ignore = b.Ignore
	x.xxx_hidden_Inline = b.Inline
	x.xxx_hidden_AsTimestamp = b.AsTimestamp
	return m0
}

var File_options_v1_crud_proto protoreflect.FileDescriptor

const file_options_v1_crud_proto_rawDesc = "" +
	"\n" +
	"\x15options/v1/crud.proto\x12\n" +
	"options.v1\x1a\x1doptions/v1/relationship.proto\"\r\n" +
	"\vFileOptions\"\x0f\n" +
	"\rMethodOptions\"\xd0\x01\n" +
	"\x0eMessageOptions\x12D\n" +
	"\x0fimplementations\x18\x01 \x03(\x0e2\x1a.options.v1.ImplementationR\x0fimplementations\x12\x1c\n" +
	"\tfieldMask\x18\x02 \x01(\tR\tfieldMask\x12\x1e\n" +
	"\n" +
	"primaryKey\x18\x03 \x03(\tR\n" +
	"primaryKey\x12\x1c\n" +
	"\tcreatedAt\x18\x04 \x01(\tR\tcreatedAt\x12\x1c\n" +
	"\tupdatedAt\x18\x05 \x01(\tR\tupdatedAt\"\x10\n" +
	"\x0eServiceOptions\"\x9e\x01\n" +
	"\fFieldOptions\x12<\n" +
	"\frelationship\x18\x01 \x01(\v2\x18.options.v1.RelationshipR\frelationship\x12\x16\n" +
	"\x06ignore\x18\x02 \x01(\bR\x06ignore\x12\x16\n" +
	"\x06inline\x18\x03 \x01(\bR\x06inline\x12 \n" +
	"\vasTimestamp\x18\x04 \x01(\bR\vasTimestamp*e\n" +
	"\x0eImplementation\x12\x1e\n" +
	"\x1aIMPLEMENTATION_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15IMPLEMENTATION_SQLITE\x10\x01\x12\x18\n" +
	"\x14IMPLEMENTATION_PGSQL\x10\x02B\xa1\x01\n" +
	"\x0ecom.options.v1B\tCrudProtoP\x01Z;github.com/samlitowitz/protoc-gen-crud/options/v1;optionsv1\xa2\x02\x03OXX\xaa\x02\n" +
	"Options.V1\xca\x02\n" +
	"Options\\V1\xe2\x02\x16Options\\V1\\GPBMetadata\xea\x02\vOptions::V1b\x06proto3"

var file_options_v1_crud_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_options_v1_crud_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_options_v1_crud_proto_goTypes = []any{
	(Implementation)(0),    // 0: options.v1.Implementation
	(*FileOptions)(nil),    // 1: options.v1.FileOptions
	(*MethodOptions)(nil),  // 2: options.v1.MethodOptions
	(*MessageOptions)(nil), // 3: options.v1.MessageOptions
	(*ServiceOptions)(nil), // 4: options.v1.ServiceOptions
	(*FieldOptions)(nil),   // 5: options.v1.FieldOptions
	(*Relationship)(nil),   // 6: options.v1.Relationship
}
var file_options_v1_crud_proto_depIdxs = []int32{
	0, // 0: options.v1.MessageOptions.implementations:type_name -> options.v1.Implementation
	6, // 1: options.v1.FieldOptions.relationship:type_name -> options.v1.Relationship
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_options_v1_crud_proto_init() }
func file_options_v1_crud_proto_init() {
	if File_options_v1_crud_proto != nil {
		return
	}
	file_options_v1_relationship_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_v1_crud_proto_rawDesc), len(file_options_v1_crud_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_options_v1_crud_proto_goTypes,
		DependencyIndexes: file_options_v1_crud_proto_depIdxs,
		EnumInfos:         file_options_v1_crud_proto_enumTypes,
		MessageInfos:      file_options_v1_crud_proto_msgTypes,
	}.Build()
	File_options_v1_crud_proto = out.File
	file_options_v1_crud_proto_goTypes = nil
	file_options_v1_crud_proto_depIdxs = nil
}
