// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: protoc-gen-crud/runtime/internal/examplepb/non_standard_names.proto

/*
Package examplepb is a repository.

It provides an interface to implement and some implementations of the interface.
*/

package examplepb
