// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/created-at/test.proto

/*
Package created_at is a repository.

PgSQL implementation.
*/

package created_at

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"google.golang.org/protobuf/types/known/timestamppb"
	pgxstdlib "github.com/jackc/pgx/v5/stdlib"
	"github.com/samlitowitz/expressions"
)

// InMemoryCreatedAtRepository is an in memory implementation of the CreatedAtRepository interface.
type PgSQLCreatedAtRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemoryCreatedAtRepository to be used.
func NewPgSQLCreatedAtRepository(db *sql.DB) (*PgSQLCreatedAtRepository, error) {
	_, ok := db.Driver().(*pgxstdlib.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *github.com/jackc/pgx/v5/stdlib/Driver")
	}
	return &PgSQLCreatedAtRepository{
		db: db,
	}, nil
}

// Create creates new CreatedAts.
// Successfully created CreatedAts are returned along with any errors that may have occurred.
func (repo *PgSQLCreatedAtRepository) Create(ctx context.Context, toCreate []*CreatedAt) ([]*CreatedAt, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	for _, createdAt := range toCreate {
		if createdAt.GetCreatedAt() != nil {
			continue
		}
		createdAt.SetCreatedAt(timestamppb.New(time.Now()))
	}
	binds := []any{}
	bindsStrs := []string{}
	bindsIdx := 1
	for _, createdAt := range toCreate {
		binds = append(binds, createdAt.GetId())
		binds = append(binds, createdAt.GetData())
		binds = append(binds, createdAt.GetCreatedAt().AsTime())
		bindsStrs = append(bindsStrs, fmt.Sprintf("($%d, $%d, $%d)", bindsIdx+0, bindsIdx+1, bindsIdx+2))
		bindsIdx += 3
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "created_at" ("id","data","created_at") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of CreatedAts matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *PgSQLCreatedAtRepository) Read(ctx context.Context, expr expressions.Expression) ([]*CreatedAt, error) {
	query := `SELECT "id","data","created_at"
		FROM "created_at"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLCreatedAt(expr, 1)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*CreatedAt
	for rows.Next() {
		createdAt := &CreatedAt_builder{}
		createdAtTime := &pgtype.Timestamp{}

		if err = rows.Scan(&createdAt.Id, &createdAt.Data, &createdAtTime); err != nil {
			return nil, err
		}
		createdAt.CreatedAt = timestamppb.New(createdAtTime.Time)

		found = append(found, createdAt.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing CreatedAts based on the defined unique identifiers.
func (repo *PgSQLCreatedAtRepository) Update(ctx context.Context, toUpdate []*CreatedAt) ([]*CreatedAt, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "created_at" SET "data" = $1,"created_at" = $2 WHERE "id" = $3`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, createdAt := range toUpdate {
		_, err = stmt.ExecContext(ctx, createdAt.GetData(), createdAt.GetCreatedAt().AsTime(), createdAt.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes CreatedAts based on the defined unique identifiers
func (repo *PgSQLCreatedAtRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "created_at"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLCreatedAt(expr, 1)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var pgsqlCreatedAtColumnNameByFieldID = map[expressions.ID]string{
	CreatedAt_Id_Field:        "id",
	CreatedAt_Data_Field:      "data",
	CreatedAt_CreatedAt_Field: "created_at",
}

func whereClauseFromExpressionForPgSQLCreatedAt(expr expressions.Expression, paramIdx int) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLCreatedAt(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLCreatedAt(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLCreatedAt(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLCreatedAt(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForPgSQLCreatedAt(expr.Operand(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLCreatedAt(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLCreatedAt(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validCreatedAtFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := pgsqlCreatedAtColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"created_at"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return fmt.Sprintf("$%d", paramIdx), []any{expr.Value()}, nil
	case expressions.Timestamp:
		return fmt.Sprintf("$%d", paramIdx), []any{time.Time(expr)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}
