// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/with-only-unknown-implementation-set/test.proto

/*
Package with_only_unknown_implementation_set is a repository.

It provides an interface to implement.
*/

package with_only_unknown_implementation_set

import (
	"context"

	"github.com/samlitowitz/expressions"
)

// These constants are used to specify fields in expressions
const (
	OnlyUnknownImplementation_Id_Field expressions.ID = "77cc65bad3767d1de6cd301f1bd97fddb1502ae5399eedc1cd5a2e3e862374ed"
)

var validOnlyUnknownImplementationFields = map[expressions.ID]struct{}{
	OnlyUnknownImplementation_Id_Field: struct{}{},
}

type OnlyUnknownImplementationRepository interface {
	// Create creates new OnlyUnknownImplementations.
	// Successfully created OnlyUnknownImplementations are returned along with any errors that may have occurred.
	Create(context.Context, []*OnlyUnknownImplementation) ([]*OnlyUnknownImplementation, error)

	// Read returns a set of OnlyUnknownImplementations matching the provided criteria
	Read(context.Context, expressions.Expression) ([]*OnlyUnknownImplementation, error)

	// Update modifies existing OnlyUnknownImplementations based on the defined unique identifiers.
	// Successfully modified OnlyUnknownImplementations are returned along with any errors that may have occurred.
	Update(context.Context, []*OnlyUnknownImplementation) ([]*OnlyUnknownImplementation, error)

	// Delete deletes OnlyUnknownImplementations matching the provided criteria
	Delete(context.Context, expressions.Expression) error
}
