// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/primary-key/test.proto

/*
Package primary_key is a repository.

PgSQL implementation.
*/

package primary_key

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	pgxstdlib "github.com/jackc/pgx/v5/stdlib"
	"github.com/samlitowitz/expressions"
)

// InMemorySAEnumRepository is an in memory implementation of the SAEnumRepository interface.
type PgSQLSAEnumRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAEnumRepository to be used.
func NewPgSQLSAEnumRepository(db *sql.DB) (*PgSQLSAEnumRepository, error) {
	_, ok := db.Driver().(*pgxstdlib.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *github.com/jackc/pgx/v5/stdlib/Driver")
	}
	return &PgSQLSAEnumRepository{
		db: db,
	}, nil
}

// Create creates new SAEnums.
// Successfully created SAEnums are returned along with any errors that may have occurred.
func (repo *PgSQLSAEnumRepository) Create(ctx context.Context, toCreate []*SAEnum) ([]*SAEnum, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	bindsIdx := 1
	for _, saenum := range toCreate {
		binds = append(binds, saenum.GetId())
		binds = append(binds, saenum.GetData())
		bindsStrs = append(bindsStrs, fmt.Sprintf("($%d, $%d)", bindsIdx+0, bindsIdx+1))
		bindsIdx += 2
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "sa_enum" ("id","data") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAEnums matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *PgSQLSAEnumRepository) Read(ctx context.Context, expr expressions.Expression) ([]*SAEnum, error) {
	query := `SELECT "id","data"
		FROM "sa_enum"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAEnum(expr, 1)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAEnum
	for rows.Next() {
		saenum := &SAEnum_builder{}

		if err = rows.Scan(&saenum.Id, &saenum.Data); err != nil {
			return nil, err
		}

		found = append(found, saenum.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAEnums based on the defined unique identifiers.
func (repo *PgSQLSAEnumRepository) Update(ctx context.Context, toUpdate []*SAEnum) ([]*SAEnum, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_enum" SET "data" = $1 WHERE "id" = $2`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, saenum := range toUpdate {
		_, err = stmt.ExecContext(ctx, saenum.GetData(), saenum.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAEnums based on the defined unique identifiers
func (repo *PgSQLSAEnumRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_enum"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAEnum(expr, 1)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var pgsqlSAEnumColumnNameByFieldID = map[expressions.ID]string{
	Saenum_Id_Field:   "id",
	Saenum_Data_Field: "data",
}

func whereClauseFromExpressionForPgSQLSAEnum(expr expressions.Expression, paramIdx int) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAEnum(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAEnum(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAEnum(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAEnum(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForPgSQLSAEnum(expr.Operand(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAEnum(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAEnum(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAEnumFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := pgsqlSAEnumColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_enum"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return fmt.Sprintf("$%d", paramIdx), []any{expr.Value()}, nil
	case expressions.Timestamp:
		return fmt.Sprintf("$%d", paramIdx), []any{time.Time(expr)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

// InMemorySAInt32Repository is an in memory implementation of the SAInt32Repository interface.
type PgSQLSAInt32Repository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAInt32Repository to be used.
func NewPgSQLSAInt32Repository(db *sql.DB) (*PgSQLSAInt32Repository, error) {
	_, ok := db.Driver().(*pgxstdlib.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *github.com/jackc/pgx/v5/stdlib/Driver")
	}
	return &PgSQLSAInt32Repository{
		db: db,
	}, nil
}

// Create creates new SAInt32s.
// Successfully created SAInt32s are returned along with any errors that may have occurred.
func (repo *PgSQLSAInt32Repository) Create(ctx context.Context, toCreate []*SAInt32) ([]*SAInt32, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	bindsIdx := 1
	for _, saint32 := range toCreate {
		binds = append(binds, saint32.GetId())
		binds = append(binds, saint32.GetData())
		bindsStrs = append(bindsStrs, fmt.Sprintf("($%d, $%d)", bindsIdx+0, bindsIdx+1))
		bindsIdx += 2
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "sa_int_32" ("id","data") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAInt32s matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *PgSQLSAInt32Repository) Read(ctx context.Context, expr expressions.Expression) ([]*SAInt32, error) {
	query := `SELECT "id","data"
		FROM "sa_int_32"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAInt32(expr, 1)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAInt32
	for rows.Next() {
		saint32 := &SAInt32_builder{}

		if err = rows.Scan(&saint32.Id, &saint32.Data); err != nil {
			return nil, err
		}

		found = append(found, saint32.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAInt32s based on the defined unique identifiers.
func (repo *PgSQLSAInt32Repository) Update(ctx context.Context, toUpdate []*SAInt32) ([]*SAInt32, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_int_32" SET "data" = $1 WHERE "id" = $2`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, saint32 := range toUpdate {
		_, err = stmt.ExecContext(ctx, saint32.GetData(), saint32.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAInt32s based on the defined unique identifiers
func (repo *PgSQLSAInt32Repository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_int_32"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAInt32(expr, 1)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var pgsqlSAInt32ColumnNameByFieldID = map[expressions.ID]string{
	Saint32_Id_Field:   "id",
	Saint32_Data_Field: "data",
}

func whereClauseFromExpressionForPgSQLSAInt32(expr expressions.Expression, paramIdx int) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAInt32(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAInt32(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAInt32(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAInt32(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForPgSQLSAInt32(expr.Operand(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAInt32(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAInt32(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAInt32Fields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := pgsqlSAInt32ColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_int_32"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return fmt.Sprintf("$%d", paramIdx), []any{expr.Value()}, nil
	case expressions.Timestamp:
		return fmt.Sprintf("$%d", paramIdx), []any{time.Time(expr)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

// InMemorySAInt64Repository is an in memory implementation of the SAInt64Repository interface.
type PgSQLSAInt64Repository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAInt64Repository to be used.
func NewPgSQLSAInt64Repository(db *sql.DB) (*PgSQLSAInt64Repository, error) {
	_, ok := db.Driver().(*pgxstdlib.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *github.com/jackc/pgx/v5/stdlib/Driver")
	}
	return &PgSQLSAInt64Repository{
		db: db,
	}, nil
}

// Create creates new SAInt64s.
// Successfully created SAInt64s are returned along with any errors that may have occurred.
func (repo *PgSQLSAInt64Repository) Create(ctx context.Context, toCreate []*SAInt64) ([]*SAInt64, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	bindsIdx := 1
	for _, saint64 := range toCreate {
		binds = append(binds, saint64.GetId())
		binds = append(binds, saint64.GetData())
		bindsStrs = append(bindsStrs, fmt.Sprintf("($%d, $%d)", bindsIdx+0, bindsIdx+1))
		bindsIdx += 2
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "sa_int_64" ("id","data") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAInt64s matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *PgSQLSAInt64Repository) Read(ctx context.Context, expr expressions.Expression) ([]*SAInt64, error) {
	query := `SELECT "id","data"
		FROM "sa_int_64"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAInt64(expr, 1)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAInt64
	for rows.Next() {
		saint64 := &SAInt64_builder{}

		if err = rows.Scan(&saint64.Id, &saint64.Data); err != nil {
			return nil, err
		}

		found = append(found, saint64.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAInt64s based on the defined unique identifiers.
func (repo *PgSQLSAInt64Repository) Update(ctx context.Context, toUpdate []*SAInt64) ([]*SAInt64, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_int_64" SET "data" = $1 WHERE "id" = $2`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, saint64 := range toUpdate {
		_, err = stmt.ExecContext(ctx, saint64.GetData(), saint64.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAInt64s based on the defined unique identifiers
func (repo *PgSQLSAInt64Repository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_int_64"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAInt64(expr, 1)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var pgsqlSAInt64ColumnNameByFieldID = map[expressions.ID]string{
	Saint64_Id_Field:   "id",
	Saint64_Data_Field: "data",
}

func whereClauseFromExpressionForPgSQLSAInt64(expr expressions.Expression, paramIdx int) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAInt64(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAInt64(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAInt64(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAInt64(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForPgSQLSAInt64(expr.Operand(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAInt64(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAInt64(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAInt64Fields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := pgsqlSAInt64ColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_int_64"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return fmt.Sprintf("$%d", paramIdx), []any{expr.Value()}, nil
	case expressions.Timestamp:
		return fmt.Sprintf("$%d", paramIdx), []any{time.Time(expr)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

// InMemorySAUint32Repository is an in memory implementation of the SAUint32Repository interface.
type PgSQLSAUint32Repository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAUint32Repository to be used.
func NewPgSQLSAUint32Repository(db *sql.DB) (*PgSQLSAUint32Repository, error) {
	_, ok := db.Driver().(*pgxstdlib.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *github.com/jackc/pgx/v5/stdlib/Driver")
	}
	return &PgSQLSAUint32Repository{
		db: db,
	}, nil
}

// Create creates new SAUint32s.
// Successfully created SAUint32s are returned along with any errors that may have occurred.
func (repo *PgSQLSAUint32Repository) Create(ctx context.Context, toCreate []*SAUint32) ([]*SAUint32, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	bindsIdx := 1
	for _, sauint32 := range toCreate {
		binds = append(binds, sauint32.GetId())
		binds = append(binds, sauint32.GetData())
		bindsStrs = append(bindsStrs, fmt.Sprintf("($%d, $%d)", bindsIdx+0, bindsIdx+1))
		bindsIdx += 2
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "sa_uint_32" ("id","data") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAUint32s matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *PgSQLSAUint32Repository) Read(ctx context.Context, expr expressions.Expression) ([]*SAUint32, error) {
	query := `SELECT "id","data"
		FROM "sa_uint_32"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAUint32(expr, 1)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAUint32
	for rows.Next() {
		sauint32 := &SAUint32_builder{}

		if err = rows.Scan(&sauint32.Id, &sauint32.Data); err != nil {
			return nil, err
		}

		found = append(found, sauint32.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAUint32s based on the defined unique identifiers.
func (repo *PgSQLSAUint32Repository) Update(ctx context.Context, toUpdate []*SAUint32) ([]*SAUint32, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_uint_32" SET "data" = $1 WHERE "id" = $2`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, sauint32 := range toUpdate {
		_, err = stmt.ExecContext(ctx, sauint32.GetData(), sauint32.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAUint32s based on the defined unique identifiers
func (repo *PgSQLSAUint32Repository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_uint_32"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAUint32(expr, 1)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var pgsqlSAUint32ColumnNameByFieldID = map[expressions.ID]string{
	Sauint32_Id_Field:   "id",
	Sauint32_Data_Field: "data",
}

func whereClauseFromExpressionForPgSQLSAUint32(expr expressions.Expression, paramIdx int) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAUint32(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAUint32(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAUint32(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAUint32(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForPgSQLSAUint32(expr.Operand(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAUint32(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAUint32(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAUint32Fields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := pgsqlSAUint32ColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_uint_32"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return fmt.Sprintf("$%d", paramIdx), []any{expr.Value()}, nil
	case expressions.Timestamp:
		return fmt.Sprintf("$%d", paramIdx), []any{time.Time(expr)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

// InMemorySAUint64Repository is an in memory implementation of the SAUint64Repository interface.
type PgSQLSAUint64Repository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAUint64Repository to be used.
func NewPgSQLSAUint64Repository(db *sql.DB) (*PgSQLSAUint64Repository, error) {
	_, ok := db.Driver().(*pgxstdlib.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *github.com/jackc/pgx/v5/stdlib/Driver")
	}
	return &PgSQLSAUint64Repository{
		db: db,
	}, nil
}

// Create creates new SAUint64s.
// Successfully created SAUint64s are returned along with any errors that may have occurred.
func (repo *PgSQLSAUint64Repository) Create(ctx context.Context, toCreate []*SAUint64) ([]*SAUint64, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	bindsIdx := 1
	for _, sauint64 := range toCreate {
		binds = append(binds, sauint64.GetId())
		binds = append(binds, sauint64.GetData())
		bindsStrs = append(bindsStrs, fmt.Sprintf("($%d, $%d)", bindsIdx+0, bindsIdx+1))
		bindsIdx += 2
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "sa_uint_64" ("id","data") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAUint64s matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *PgSQLSAUint64Repository) Read(ctx context.Context, expr expressions.Expression) ([]*SAUint64, error) {
	query := `SELECT "id","data"
		FROM "sa_uint_64"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAUint64(expr, 1)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAUint64
	for rows.Next() {
		sauint64 := &SAUint64_builder{}

		if err = rows.Scan(&sauint64.Id, &sauint64.Data); err != nil {
			return nil, err
		}

		found = append(found, sauint64.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAUint64s based on the defined unique identifiers.
func (repo *PgSQLSAUint64Repository) Update(ctx context.Context, toUpdate []*SAUint64) ([]*SAUint64, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_uint_64" SET "data" = $1 WHERE "id" = $2`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, sauint64 := range toUpdate {
		_, err = stmt.ExecContext(ctx, sauint64.GetData(), sauint64.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAUint64s based on the defined unique identifiers
func (repo *PgSQLSAUint64Repository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_uint_64"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAUint64(expr, 1)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var pgsqlSAUint64ColumnNameByFieldID = map[expressions.ID]string{
	Sauint64_Id_Field:   "id",
	Sauint64_Data_Field: "data",
}

func whereClauseFromExpressionForPgSQLSAUint64(expr expressions.Expression, paramIdx int) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAUint64(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAUint64(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAUint64(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAUint64(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForPgSQLSAUint64(expr.Operand(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAUint64(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAUint64(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAUint64Fields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := pgsqlSAUint64ColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_uint_64"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return fmt.Sprintf("$%d", paramIdx), []any{expr.Value()}, nil
	case expressions.Timestamp:
		return fmt.Sprintf("$%d", paramIdx), []any{time.Time(expr)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

// InMemorySAStringRepository is an in memory implementation of the SAStringRepository interface.
type PgSQLSAStringRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemorySAStringRepository to be used.
func NewPgSQLSAStringRepository(db *sql.DB) (*PgSQLSAStringRepository, error) {
	_, ok := db.Driver().(*pgxstdlib.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *github.com/jackc/pgx/v5/stdlib/Driver")
	}
	return &PgSQLSAStringRepository{
		db: db,
	}, nil
}

// Create creates new SAStrings.
// Successfully created SAStrings are returned along with any errors that may have occurred.
func (repo *PgSQLSAStringRepository) Create(ctx context.Context, toCreate []*SAString) ([]*SAString, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	bindsIdx := 1
	for _, sastring := range toCreate {
		binds = append(binds, sastring.GetId())
		binds = append(binds, sastring.GetData())
		bindsStrs = append(bindsStrs, fmt.Sprintf("($%d, $%d)", bindsIdx+0, bindsIdx+1))
		bindsIdx += 2
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "sa_string" ("id","data") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of SAStrings matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *PgSQLSAStringRepository) Read(ctx context.Context, expr expressions.Expression) ([]*SAString, error) {
	query := `SELECT "id","data"
		FROM "sa_string"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAString(expr, 1)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*SAString
	for rows.Next() {
		sastring := &SAString_builder{}

		if err = rows.Scan(&sastring.Id, &sastring.Data); err != nil {
			return nil, err
		}

		found = append(found, sastring.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing SAStrings based on the defined unique identifiers.
func (repo *PgSQLSAStringRepository) Update(ctx context.Context, toUpdate []*SAString) ([]*SAString, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "sa_string" SET "data" = $1 WHERE "id" = $2`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, sastring := range toUpdate {
		_, err = stmt.ExecContext(ctx, sastring.GetData(), sastring.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes SAStrings based on the defined unique identifiers
func (repo *PgSQLSAStringRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "sa_string"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLSAString(expr, 1)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var pgsqlSAStringColumnNameByFieldID = map[expressions.ID]string{
	Sastring_Id_Field:   "id",
	Sastring_Data_Field: "data",
}

func whereClauseFromExpressionForPgSQLSAString(expr expressions.Expression, paramIdx int) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAString(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAString(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAString(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAString(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForPgSQLSAString(expr.Operand(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLSAString(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLSAString(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validSAStringFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := pgsqlSAStringColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"sa_string"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return fmt.Sprintf("$%d", paramIdx), []any{expr.Value()}, nil
	case expressions.Timestamp:
		return fmt.Sprintf("$%d", paramIdx), []any{time.Time(expr)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}

// InMemoryMAAllRepository is an in memory implementation of the MAAllRepository interface.
type PgSQLMAAllRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemoryMAAllRepository to be used.
func NewPgSQLMAAllRepository(db *sql.DB) (*PgSQLMAAllRepository, error) {
	_, ok := db.Driver().(*pgxstdlib.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *github.com/jackc/pgx/v5/stdlib/Driver")
	}
	return &PgSQLMAAllRepository{
		db: db,
	}, nil
}

// Create creates new MAAlls.
// Successfully created MAAlls are returned along with any errors that may have occurred.
func (repo *PgSQLMAAllRepository) Create(ctx context.Context, toCreate []*MAAll) ([]*MAAll, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	bindsIdx := 1
	for _, maall := range toCreate {
		binds = append(binds, maall.GetIdInt32())
		binds = append(binds, maall.GetIdInt64())
		binds = append(binds, maall.GetIdUint32())
		binds = append(binds, maall.GetIdUint64())
		binds = append(binds, maall.GetIdString())
		binds = append(binds, maall.GetIdEnum())
		binds = append(binds, maall.GetData())
		bindsStrs = append(bindsStrs, fmt.Sprintf("($%d, $%d, $%d, $%d, $%d, $%d, $%d)", bindsIdx+0, bindsIdx+1, bindsIdx+2, bindsIdx+3, bindsIdx+4, bindsIdx+5, bindsIdx+6))
		bindsIdx += 7
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "ma_all" ("id_int_32","id_int_64","id_uint_32","id_uint_64","id_string","id_enum","data") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of MAAlls matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *PgSQLMAAllRepository) Read(ctx context.Context, expr expressions.Expression) ([]*MAAll, error) {
	query := `SELECT "id_int_32","id_int_64","id_uint_32","id_uint_64","id_string","id_enum","data"
		FROM "ma_all"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLMAAll(expr, 1)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*MAAll
	for rows.Next() {
		maall := &MAAll_builder{}

		if err = rows.Scan(&maall.IdInt32, &maall.IdInt64, &maall.IdUint32, &maall.IdUint64, &maall.IdString, &maall.IdEnum, &maall.Data); err != nil {
			return nil, err
		}

		found = append(found, maall.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing MAAlls based on the defined unique identifiers.
func (repo *PgSQLMAAllRepository) Update(ctx context.Context, toUpdate []*MAAll) ([]*MAAll, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "ma_all" SET "data" = $1 WHERE "id_int_32" = $2 AND "id_int_64" = $3 AND "id_uint_32" = $4 AND "id_uint_64" = $5 AND "id_string" = $6 AND "id_enum" = $7`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, maall := range toUpdate {
		_, err = stmt.ExecContext(ctx, maall.GetData(), maall.GetIdInt32(), maall.GetIdInt64(), maall.GetIdUint32(), maall.GetIdUint64(), maall.GetIdString(), maall.GetIdEnum())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes MAAlls based on the defined unique identifiers
func (repo *PgSQLMAAllRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "ma_all"`
	clauses, binds, err := whereClauseFromExpressionForPgSQLMAAll(expr, 1)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var pgsqlMAAllColumnNameByFieldID = map[expressions.ID]string{
	Maall_IdInt32_Field:  "id_int_32",
	Maall_IdInt64_Field:  "id_int_64",
	Maall_IdUint32_Field: "id_uint_32",
	Maall_IdUint64_Field: "id_uint_64",
	Maall_IdString_Field: "id_string",
	Maall_IdEnum_Field:   "id_enum",
	Maall_Data_Field:     "data",
}

func whereClauseFromExpressionForPgSQLMAAll(expr expressions.Expression, paramIdx int) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLMAAll(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLMAAll(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLMAAll(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLMAAll(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForPgSQLMAAll(expr.Operand(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForPgSQLMAAll(expr.Left(), paramIdx)
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForPgSQLMAAll(expr.Right(), paramIdx+len(leftBinds))
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validMAAllFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := pgsqlMAAllColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"ma_all"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return fmt.Sprintf("$%d", paramIdx), []any{expr.Value()}, nil
	case expressions.Timestamp:
		return fmt.Sprintf("$%d", paramIdx), []any{time.Time(expr)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}
