// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: protoc-gen-crud/assets/protobuf/examples/book-list/books.proto

/*
Package book_list is a repository.

It provides an interface to implement and some implementations of the interface.
*/

package book_list

type AuthorRepository interface {
	/*
		&descriptor.CRUD{Message:(*descriptor.Message)(0xc0004567e0), Operations:map[options.Operation]struct {}{}, UniqueIdentifiers:map[string][]*descriptor.Field{}}
	*/

}
