// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: protoc-gen-crud/assets/protobuf/examples/book-list/books.proto

/*
Package book_list is a repository.

It provides an interface to implement and some implementations of the interface.
*/

package book_list

type AuthorRepository interface {
}

// TODO: Add Comment
type InMemoryAuthorRepository struct {
	authorById map[string]*Author
}

// TODO: Add Comment
func NewInMemoryAuthorRepository() *InMemoryAuthorRepository {
	return &InMemoryAuthorRepository{}
}

type BookRepository interface {
}
