// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: protoc-gen-crud/assets/protobuf/examples/book-list/books.proto

/*
Package book_list is a repository.

It provides an interface to implement and some implementations of the interface.
*/

package book_list

import (
	"bytes"
	"encoding/binary"
)

type AuthorRepository interface {
	// Create creates new Authors.
	// Successfully created Authors are returned along with any errors that may have occurred.
	Create([]*Author) ([]*Author, error)

	// Read returns a set of Authors matching the provided criteria
	// Read is incomplete and it should be considered unstable
	// Use where clauses
	Read() ([]*Author, error)

	// Update modifies existing Authors based on the defined unique identifiers.
	// Successfully modified Authors are returned along with any errors that may have occurred.
	Update([]*Author) ([]*Author, error)

	// Delete deletes Authors based on the defined unique identifiers
	// Delete is incomplete and it should be considered unstable
	// Use where clauses
	Delete([]*Author) error
}

// InMemoryAuthorRepository is an in memory implementation of the AuthorRepository interface.
type InMemoryAuthorRepository struct {
	authorById map[string]*Author

	authorByIdName map[string]*Author
}

// NewInMemory creates a new InMemoryAuthorRepository to be used.
func NewInMemoryAuthorRepository() *InMemoryAuthorRepository {
	return &InMemoryAuthorRepository{
		authorById: make(map[string]*Author), authorByIdName: make(map[string]*Author),
	}
}

// Create creates new Authors.
// Successfully created Authors are returned along with any errors that may have occurred.
func (repo *InMemoryAuthorRepository) Create([]*Author) ([]*Author, error) {
	panic("not implemented")
}

// Read returns a set of Authors matching the provided criteria
// Read is incomplete and it should be considered unstable
// Use where clauses
func (repo *InMemoryAuthorRepository) Read() ([]*Author, error) {
	panic("not implemented")
}

// Update modifies existing Authors based on the defined unique identifiers.
func (repo *InMemoryAuthorRepository) Update([]*Author) ([]*Author, error) {
	panic("not implemented")
}

// Delete deletes Authors based on the defined unique identifiers
// Delete is incomplete and it should be considered unstable
// Use where clauses
func (repo *InMemoryAuthorRepository) Delete([]*Author) error {
	// TODO: Get structs by uid(s)
	// TODO: Remove found structs
	// TODO: Return error(s)
	panic("not implemented")
}

func getAuthorById(authors []*Author) (map[string]*Author, error) {
	authorById := make(map[string]*Author)
	for _, def := range authors {
		key := def.Id
		authorById[key] = def
	}
	return authorById, nil
}

func getAuthorByIdName(authors []*Author) (map[string]*Author, error) {
	authorByIdName := make(map[string]*Author)
	for _, def := range authors {
		buf := bytes.Buffer{}
		err := binary.Write(buf, binary.LittleEndian, def.id)
		if err != nil {
			return nil, err
		}

		err := binary.Write(buf, binary.LittleEndian, def.name)
		if err != nil {
			return nil, err
		}
		key := buf.String()
		authorByIdName[key] = def
	}
	return authorByIdName, nil
}

type BookRepository interface {
}
