// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: options/v1/relationships/direction.proto

package relationships

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Direction int32

const (
	Direction_UNKNOWN_DIRECTION Direction = 0
	Direction_BIDIRECTIONAL     Direction = 1
	Direction_UNIDIRECTIONAL    Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "UNKNOWN_DIRECTION",
		1: "BIDIRECTIONAL",
		2: "UNIDIRECTIONAL",
	}
	Direction_value = map[string]int32{
		"UNKNOWN_DIRECTION": 0,
		"BIDIRECTIONAL":     1,
		"UNIDIRECTIONAL":    2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_options_v1_relationships_direction_proto_enumTypes[0].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_options_v1_relationships_direction_proto_enumTypes[0]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_options_v1_relationships_direction_proto protoreflect.FileDescriptor

const file_options_v1_relationships_direction_proto_rawDesc = "" +
	"\n" +
	"(options/v1/relationships/direction.proto\x12\x18options.v1.relationships*I\n" +
	"\tDirection\x12\x15\n" +
	"\x11UNKNOWN_DIRECTION\x10\x00\x12\x11\n" +
	"\rBIDIRECTIONAL\x10\x01\x12\x12\n" +
	"\x0eUNIDIRECTIONAL\x10\x02B\xf1\x01\n" +
	"\x1ccom.options.v1.relationshipsB\x0eDirectionProtoP\x01Z?github.com/samlitowitz/protoc-gen-crud/options/v1/relationships\xa2\x02\x03OVR\xaa\x02\x18Options.V1.Relationships\xca\x02\x18Options\\V1\\Relationships\xe2\x02$Options\\V1\\Relationships\\GPBMetadata\xea\x02\x1aOptions::V1::Relationshipsb\x06proto3"

var file_options_v1_relationships_direction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_options_v1_relationships_direction_proto_goTypes = []any{
	(Direction)(0), // 0: options.v1.relationships.Direction
}
var file_options_v1_relationships_direction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_v1_relationships_direction_proto_init() }
func file_options_v1_relationships_direction_proto_init() {
	if File_options_v1_relationships_direction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_v1_relationships_direction_proto_rawDesc), len(file_options_v1_relationships_direction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_options_v1_relationships_direction_proto_goTypes,
		DependencyIndexes: file_options_v1_relationships_direction_proto_depIdxs,
		EnumInfos:         file_options_v1_relationships_direction_proto_enumTypes,
	}.Build()
	File_options_v1_relationships_direction_proto = out.File
	file_options_v1_relationships_direction_proto_goTypes = nil
	file_options_v1_relationships_direction_proto_depIdxs = nil
}
