// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: options/v1/relationships/type.proto

package relationships

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_UNKNOWN_TYPE Type = 0
	Type_ONE_TO_ONE   Type = 1
	Type_ONE_TO_MANY  Type = 2
	Type_MANY_TO_ONE  Type = 3
	Type_MANY_TO_MANY Type = 4
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "UNKNOWN_TYPE",
		1: "ONE_TO_ONE",
		2: "ONE_TO_MANY",
		3: "MANY_TO_ONE",
		4: "MANY_TO_MANY",
	}
	Type_value = map[string]int32{
		"UNKNOWN_TYPE": 0,
		"ONE_TO_ONE":   1,
		"ONE_TO_MANY":  2,
		"MANY_TO_ONE":  3,
		"MANY_TO_MANY": 4,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_options_v1_relationships_type_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_options_v1_relationships_type_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_options_v1_relationships_type_proto protoreflect.FileDescriptor

const file_options_v1_relationships_type_proto_rawDesc = "" +
	"\n" +
	"#options/v1/relationships/type.proto\x12\x18options.v1.relationships*\\\n" +
	"\x04Type\x12\x10\n" +
	"\fUNKNOWN_TYPE\x10\x00\x12\x0e\n" +
	"\n" +
	"ONE_TO_ONE\x10\x01\x12\x0f\n" +
	"\vONE_TO_MANY\x10\x02\x12\x0f\n" +
	"\vMANY_TO_ONE\x10\x03\x12\x10\n" +
	"\fMANY_TO_MANY\x10\x04B\xec\x01\n" +
	"\x1ccom.options.v1.relationshipsB\tTypeProtoP\x01Z?github.com/samlitowitz/protoc-gen-crud/options/v1/relationships\xa2\x02\x03OVR\xaa\x02\x18Options.V1.Relationships\xca\x02\x18Options\\V1\\Relationships\xe2\x02$Options\\V1\\Relationships\\GPBMetadata\xea\x02\x1aOptions::V1::Relationshipsb\x06proto3"

var file_options_v1_relationships_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_options_v1_relationships_type_proto_goTypes = []any{
	(Type)(0), // 0: options.v1.relationships.Type
}
var file_options_v1_relationships_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_options_v1_relationships_type_proto_init() }
func file_options_v1_relationships_type_proto_init() {
	if File_options_v1_relationships_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_options_v1_relationships_type_proto_rawDesc), len(file_options_v1_relationships_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_options_v1_relationships_type_proto_goTypes,
		DependencyIndexes: file_options_v1_relationships_type_proto_depIdxs,
		EnumInfos:         file_options_v1_relationships_type_proto_enumTypes,
	}.Build()
	File_options_v1_relationships_type_proto = out.File
	file_options_v1_relationships_type_proto_goTypes = nil
	file_options_v1_relationships_type_proto_depIdxs = nil
}
