// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/updated-at/test.proto

/*
Package updated_at is a repository.

SQLite implementation.
*/

package updated_at

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"
	"modernc.org/sqlite"
	"github.com/samlitowitz/expressions"
)

// InMemoryUpdatedAtRepository is an in memory implementation of the UpdatedAtRepository interface.
type SQLiteUpdatedAtRepository struct {
	db *sql.DB
}

// NewInMemory creates a new InMemoryUpdatedAtRepository to be used.
func NewSQLiteUpdatedAtRepository(db *sql.DB) (*SQLiteUpdatedAtRepository, error) {
	_, ok := db.Driver().(*sqlite.Driver)
	if !ok {
		return nil, fmt.Errorf("invalid driver, must be of type *modernc.org/sqlite.Driver")
	}
	return &SQLiteUpdatedAtRepository{
		db: db,
	}, nil
}

// Create creates new UpdatedAts.
// Successfully created UpdatedAts are returned along with any errors that may have occurred.
func (repo *SQLiteUpdatedAtRepository) Create(ctx context.Context, toCreate []*UpdatedAt) ([]*UpdatedAt, error) {
	if len(toCreate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	binds := []any{}
	bindsStrs := []string{}
	for _, updatedAt := range toCreate {
		binds = append(binds, updatedAt.GetId())
		binds = append(binds, updatedAt.GetData())
		binds = append(binds, updatedAt.GetUpdatedAt().AsTime().Format(time.RFC3339))
		bindsStrs = append(bindsStrs, "(?,?,?)")
	}
	_, err = tx.ExecContext(
		ctx,
		fmt.Sprintf(
			`INSERT INTO "updated_at" ("id","data","updated_at") VALUES
			%s`,
			strings.Join(bindsStrs, ",\n"),
		),
		binds...,
	)
	if err != nil {
		return nil, err
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toCreate, nil
}

// Read returns a set of UpdatedAts matching the provided criteria
// Read is incomplete and it should be considered unstable
func (repo *SQLiteUpdatedAtRepository) Read(ctx context.Context, expr expressions.Expression) ([]*UpdatedAt, error) {
	query := `SELECT "id","data","updated_at"
		FROM "updated_at"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteUpdatedAt(expr)
	if err != nil {
		return nil, err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return nil, err
	}
	rows, err := stmt.QueryContext(ctx, binds...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var found []*UpdatedAt
	for rows.Next() {
		updatedAt := &UpdatedAt_builder{}
		var updatedAtTimeStr string

		if err = rows.Scan(&updatedAt.Id, &updatedAt.Data, &updatedAtTimeStr); err != nil {
			return nil, err
		}

		updatedAtTime, err := time.Parse(time.RFC3339, updatedAtTimeStr)
		if err != nil {
			return nil, err
		}
		updatedAt.UpdatedAt = timestamppb.New(updatedAtTime)

		found = append(found, updatedAt.Build())
	}
	if err = rows.Err(); err != nil {
		return nil, err
	}
	return found, nil
}

// Update modifies existing UpdatedAts based on the defined unique identifiers.
func (repo *SQLiteUpdatedAtRepository) Update(ctx context.Context, toUpdate []*UpdatedAt) ([]*UpdatedAt, error) {
	if len(toUpdate) == 0 {
		return nil, nil
	}
	tx, err := repo.db.BeginTx(ctx, &sql.TxOptions{Isolation: sql.LevelSerializable})
	if err != nil {
		return nil, err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(
		`UPDATE "updated_at" SET "data" = ?,"updated_at" = ? WHERE "id" = ?`,
	)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	for _, updatedAt := range toUpdate {
		if updatedAt.GetUpdatedAt() != nil {
			continue
		}
		updatedAt.SetUpdatedAt(timestamppb.New(time.Now()))
	}
	for _, updatedAt := range toUpdate {
		_, err = stmt.ExecContext(ctx, updatedAt.GetData(), updatedAt.GetUpdatedAt().AsTime().Format(time.RFC3339), updatedAt.GetId())
		if err != nil {
			return nil, err
		}
	}
	err = tx.Commit()
	if err != nil {
		return nil, err
	}
	return toUpdate, nil
}

// Delete deletes UpdatedAts based on the defined unique identifiers
func (repo *SQLiteUpdatedAtRepository) Delete(ctx context.Context, expr expressions.Expression) error {
	query := `DELETE FROM "updated_at"`
	clauses, binds, err := whereClauseFromExpressionForSQLiteUpdatedAt(expr)
	if err != nil {
		return err
	}
	if clauses != "" {
		query += "\nWHERE\n" + clauses
	}
	stmt, err := repo.db.Prepare(query)
	if err != nil {
		return err
	}
	_, err = stmt.ExecContext(ctx, binds...)
	if err != nil {
		return err
	}
	return nil
}

var sqliteUpdatedAtColumnNameByFieldID = map[expressions.ID]string{
	UpdatedAt_Id_Field:        "id",
	UpdatedAt_Data_Field:      "data",
	UpdatedAt_UpdatedAt_Field: "updated_at",
}

func whereClauseFromExpressionForSQLiteUpdatedAt(expr expressions.Expression) (string, []any, error) {
	if expr == nil {
		return "", nil, nil
	}
	switch expr := expr.(type) {
	case *expressions.And:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteUpdatedAt(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteUpdatedAt(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s AND %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Or:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteUpdatedAt(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteUpdatedAt(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s OR %s", left, right), append(leftBinds, rightBinds...), nil
	case *expressions.Not:
		operand, binds, err := whereClauseFromExpressionForSQLiteUpdatedAt(expr.Operand())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("NOT %s", operand), binds, nil

	case *expressions.Equals:
		left, leftBinds, err := whereClauseFromExpressionForSQLiteUpdatedAt(expr.Left())
		if err != nil {
			return "", nil, err
		}
		right, rightBinds, err := whereClauseFromExpressionForSQLiteUpdatedAt(expr.Right())
		if err != nil {
			return "", nil, err
		}
		return fmt.Sprintf("%s = %s", left, right), append(leftBinds, rightBinds...), nil

	case *expressions.Identifier:
		if _, ok := validUpdatedAtFields[expr.ID()]; !ok {
			return "", nil, fmt.Errorf("invalid field id: %s", expr.ID())
		}
		colName, ok := sqliteUpdatedAtColumnNameByFieldID[expr.ID()]
		if !ok {
			return "", nil, fmt.Errorf("missing meta-data: field id: %s", expr.ID())
		}
		return fmt.Sprintf(`"updated_at"."%s"`, colName), nil, nil
	case *expressions.Scalar:
		return "?", []any{expr.Value()}, nil
	case expressions.Timestamp:
		return "?", []any{time.Time(expr).Format(time.RFC3339)}, nil
	default:
		return "", nil, fmt.Errorf("unknown expression")
	}
}
