// Code generated by protoc-gen-go-crud. DO NOT EDIT.
// source: test-cases/updated-at/test.proto

/*
Package updated_at is a repository.

It provides an interface to implement.
*/

package updated_at

import (
	"context"

	"github.com/samlitowitz/expressions"
)

// These constants are used to specify fields in expressions
const (
	UpdatedAt_Id_Field        expressions.ID = "f3993e68f73e420da045e8ee92d04137b7eee1aef5b704a372371eb734825175"
	UpdatedAt_UpdatedAt_Field expressions.ID = "f59c9519de374ae29d212538fbc20ed0f57e3df4e8d606622ac0a323d62e4988"
	UpdatedAt_Data_Field      expressions.ID = "ceabdd24edde7b8e0cbad683fbe5701cbe68c074b6ef9743657f5d3b35cd2403"
)

var validUpdatedAtFields = map[expressions.ID]struct{}{
	UpdatedAt_Id_Field:        struct{}{},
	UpdatedAt_UpdatedAt_Field: struct{}{},
	UpdatedAt_Data_Field:      struct{}{},
}

type UpdatedAtRepository interface {
	// Create creates new UpdatedAts.
	// Successfully created UpdatedAts are returned along with any errors that may have occurred.
	Create(context.Context, []*UpdatedAt) ([]*UpdatedAt, error)

	// Read returns a set of UpdatedAts matching the provided criteria
	Read(context.Context, expressions.Expression) ([]*UpdatedAt, error)

	// Update modifies existing UpdatedAts based on the defined unique identifiers.
	// Successfully modified UpdatedAts are returned along with any errors that may have occurred.
	Update(context.Context, []*UpdatedAt) ([]*UpdatedAt, error)

	// Delete deletes UpdatedAts matching the provided criteria
	Delete(context.Context, expressions.Expression) error
}
